%% ============================================================
% FOG_thermal_v7.m
% Interferometryczny zyroskop swiatlowodowy - model v7
% MATLAB / Simulink R2023b
%
% CEL:
% - zbadac temperaturowy dryft scale factor,
% - dodac czysty efekt Shupe dla niejednorodnego pola temperatury,
% - porownac materialy formy cewki pod BOM,
% - wyznaczyc wymaganie na izolacje termiczna,
% - wyznaczyc wymagania na czujniki temperatury i ich odczyt,
% - zbudowac thermal BOM / acceptance plan.
%
% v7 jest modelem projektowym i wrazliwosciowym.
% NIE modeluje jeszcze pelnego termo-mechanicznego stresu coatingu,
% kleju i pottingu. Roznice CTE sa traktowane jako jawny stress-risk
% proxy, a nie jako pelny model fotoelastyczny.
%
% Efekt Shupe:
% Omega_E(t) = n/(D L) * (dn/dT + n*alpha_fiber)
%              * integral[ dT/dt(l,t) * (L-2l) dl ]
%
% Dla uzwojenia symetrycznego uzywamy jawnego parametru
% winding_asymmetry_fraction. Nie oznacza on gwarantowanej redukcji
% konkretnego realnego QAD, tylko model niedoskonalosci symetrii.
%% ============================================================

clc
close all
bdclose('all')

disp("==============================================")
disp(" FOG v7 - TEMPERATURA / SHUPE / THERMAL BOM")
disp("==============================================")

%% ============================================================
% PARAMETRY ZABLOKOWANE Z v6.3
%% ============================================================

c = 299792458;
lambda = 1550e-9;

L0 = 1000;
D0 = 159.394500392266e-3;

ng0 = 1.4682;

K_sag0 = ...
    2*pi*L0*D0/(lambda*c);

f_mod = 20e3;
beta_target = 1.84;

tau0 = ng0*L0/c;

phi0 = ...
    beta_target/(2*abs(sin(pi*f_mod*tau0)));

J1beta0 = besselj(1,beta_target);

Tref_C = 25;

% Cel detekcji projektu:
target_rate_deg_s = 1e-4;
target_rate_deg_h = target_rate_deg_s*3600;

% Alokujemy 1/3 docelowego sygnalu na thermal error.
thermal_budget_deg_h = ...
    target_rate_deg_h/3;

% Maksymalna predkosc do testu scale-factor.
Omega_fullscale_test_deg_s = 20;

%% ============================================================
% WLASCIWOSCI WLOKNA KRZEMIONKOWEGO
%% ============================================================

% Efektywny indeks do Shupe.
n_eff = 1.4445;

% Benchmark room-temperature 1550 nm.
dn_dT = 8.4e-6;                 % 1/K
alpha_fiber = 0.55e-6;          % 1/K

% Do tau(T) stosujemy ten sam rzad thermo-optic.
dng_dT = dn_dT;

%% ============================================================
% MATERIALY FORMERA - BENCHMARKI
%
% Nie sa to jeszcze konkretne partie materialu zakupowego.
% Po wyborze klasy wymagamy datasheet konkretnej plyty/pretow.
%% ============================================================

material = [ ...
    "Al6061-T6"; ...
    "Invar36"; ...
    "G10-FR4"; ...
    "POM-C"; ...
    "FusedSilica benchmark" ...
    ];

CTE_1_K = [ ...
    23.6e-6; ...
    1.30e-6; ...
    9.0e-6; ...
    110e-6; ...
    0.55e-6 ...
    ];

k_W_mK = [ ...
    167; ...
    10.5; ...
    0.30; ...
    0.31; ...
    1.38 ...
    ];

rho_kg_m3 = [ ...
    2700; ...
    8055; ...
    1820; ...
    1410; ...
    2203 ...
    ];

cp_J_kgK = [ ...
    896; ...
    515; ...
    1000; ...
    1500; ...
    703 ...
    ];

material_note = [ ...
    "very high conductivity; high CTE mismatch to silica"; ...
    "low CTE; moderate conductivity; precision-instrument class"; ...
    "moderate CTE; low through-thickness conductivity"; ...
    "easy machining but very high CTE"; ...
    "reference only; not default mechanical spool" ...
    ];

Nm = numel(material);

thermal_diffusivity_m2_s = ...
    k_W_mK./(rho_kg_m3.*cp_J_kgK);

CTE_mismatch_ppm_K = ...
    abs(CTE_1_K-alpha_fiber)*1e6;

%% ============================================================
% v7A - JEDNORODNA TEMPERATURA / SCALE FACTOR
%% ============================================================

disp("")
disp("==============================================")
disp(" v7A - UNIFORM TEMPERATURE SCALE FACTOR")
disp("==============================================")

T_sweep_C = (-10:5:60)';
Nt = numel(T_sweep_C);

rows = Nm*Nt;

matCol = strings(rows,1);
tempCol = zeros(rows,1);
diameter_mm = zeros(rows,1);
length_m = zeros(rows,1);
ngCol = zeros(rows,1);
betaCol = zeros(rows,1);
scaleFactor = zeros(rows,1);
scaleError_ppm = zeros(rows,1);
errorAt1_deg_s = zeros(rows,1);
errorAt20_deg_s = zeros(rows,1);

uniformCoeff_ppm_K = zeros(Nm,1);
allowedSensorError_C = zeros(Nm,1);

row = 0;

for km = 1:Nm

    alphaFormer = CTE_1_K(km);

    for kt = 1:Nt

        row = row+1;

        dT = T_sweep_C(kt)-Tref_C;

        Lt = ...
            L0*(1+alpha_fiber*dT);

        Dt = ...
            D0*(1+alphaFormer*dT);

        ngt = ...
            ng0+dng_dT*dT;

        taut = ...
            ngt*Lt/c;

        betat = ...
            2*phi0*abs(sin(pi*f_mod*taut));

        Kt = ...
            2*pi*Lt*Dt/(lambda*c);

        modulationGainRatio = ...
            besselj(1,betat)/J1beta0;

        sf = ...
            (Kt/K_sag0)*modulationGainRatio;

        matCol(row) = material(km);
        tempCol(row) = T_sweep_C(kt);
        diameter_mm(row) = Dt*1e3;
        length_m(row) = Lt;
        ngCol(row) = ngt;
        betaCol(row) = betat;
        scaleFactor(row) = sf;
        scaleError_ppm(row) = (sf-1)*1e6;
        errorAt1_deg_s(row) = (sf-1)*1;
        errorAt20_deg_s(row) = ...
            (sf-1)*Omega_fullscale_test_deg_s;
    end

    % Lokalny wspolczynnik w 25 C.
    epsT = 0.01;

    sfPlus = thermalScaleFactor( ...
        Tref_C+epsT,Tref_C, ...
        L0,D0,ng0,dng_dT,alpha_fiber,alphaFormer, ...
        c,lambda,f_mod,phi0,K_sag0,J1beta0);

    sfMinus = thermalScaleFactor( ...
        Tref_C-epsT,Tref_C, ...
        L0,D0,ng0,dng_dT,alpha_fiber,alphaFormer, ...
        c,lambda,f_mod,phi0,K_sag0,J1beta0);

    coeff = ...
        (sfPlus-sfMinus)/(2*epsT);

    uniformCoeff_ppm_K(km) = ...
        coeff*1e6;

    allowedSensorError_C(km) = ...
        target_rate_deg_s / ...
        (Omega_fullscale_test_deg_s*abs(coeff));
end

uniformSweep = table( ...
    matCol, ...
    tempCol, ...
    diameter_mm, ...
    length_m, ...
    ngCol, ...
    betaCol, ...
    scaleFactor, ...
    scaleError_ppm, ...
    errorAt1_deg_s, ...
    errorAt20_deg_s, ...
    'VariableNames', ...
    { ...
    'Former_material', ...
    'Temperature_C', ...
    'Coil_diameter_mm', ...
    'Fiber_length_m', ...
    'Group_index', ...
    'Beta_rad', ...
    'Relative_scale_factor', ...
    'Scale_error_ppm', ...
    'Error_at_1deg_s_deg_s', ...
    'Error_at_20deg_s_deg_s' ...
    });

writetable( ...
    uniformSweep, ...
    'FOG_v7_uniform_temperature_sweep.csv');

%% ============================================================
% PT100 KLASY - DO SCALE-FACTOR COMPENSATION
%% ============================================================

ptClass = [ ...
    "AA"; ...
    "A"; ...
    "B" ...
    ];

ptTolAt25_C = [ ...
    0.10+0.0017*25; ...
    0.15+0.0020*25; ...
    0.30+0.0050*25 ...
    ];

ptAA_tol = ptTolAt25_C(1);
ptA_tol = ptTolAt25_C(2);
ptB_tol = ptTolAt25_C(3);

passPtA = ...
    allowedSensorError_C >= ptA_tol;

passPtAA = ...
    allowedSensorError_C >= ptAA_tol;

%% ============================================================
% v7B - SHUPE: RADIALNY TRANSIENT CIEPLNY
%% ============================================================

disp("")
disp("==============================================")
disp(" v7B - SHUPE TRANSIENT / FORMER MATERIAL")
disp("==============================================")

% Geometria warstw z v6.3.
layerLength_m = [ ...
    54.1354910668731; ...
    54.3042699905946; ...
    54.4730489143160; ...
    54.6418278380375; ...
    54.8106067617590; ...
    54.9793856854804; ...
    55.1481646092019; ...
    55.3169435329233; ...
    55.4857224566448; ...
    55.6545013803662; ...
    55.8232803040877; ...
    55.9920592278092; ...
    56.1608381515306; ...
    56.3296170752521; ...
    56.4983959989735; ...
    56.6671749226950; ...
    56.8359538464164; ...
    56.7427182370387 ...
    ];

Nlayers = numel(layerLength_m);

layerEdges_m = ...
    [0;cumsum(layerLength_m)];

% Dokladna calka (L-2l) dl po danym zakresie wlokna.
shupeWeight_m2 = zeros(Nlayers,1);

for kl = 1:Nlayers

    a = layerEdges_m(kl);
    b = layerEdges_m(kl+1);

    shupeWeight_m2(kl) = ...
        L0*(b-a) - (b^2-a^2);
end

shupeCoeff = ...
    n_eff/(D0*L0) * ...
    (dn_dT+n_eff*alpha_fiber);

% Model niedoskonalosci uzwojenia symetrycznego.
winding_asymmetry_fraction = 0.02;

former_wall_m = 5e-3;

% tau_outer reprezentuje thermal enclosure / insulation,
% a nie stala materialowa.
tauOuterSweep_s = [15 30 60 120]';
rampSweep_C_min = [1 5]';

thermal_step_C = 10;

dtThermal_s = 0.1;
Tend_s = 900;

Nramp = numel(rampSweep_C_min);
Ntau = numel(tauOuterSweep_s);

NrowsThermal = Nm*Nramp*Ntau;

thMaterial = strings(NrowsThermal,1);
thRamp = zeros(NrowsThermal,1);
thTauOuter = zeros(NrowsThermal,1);
thTauInner = zeros(NrowsThermal,1);
thMaxSeq_deg_h = zeros(NrowsThermal,1);
thMaxQAD_deg_h = zeros(NrowsThermal,1);
thRMSQAD_deg_h = zeros(NrowsThermal,1);
thRequiredAsymPct = zeros(NrowsThermal,1);
thPassBudget = false(NrowsThermal,1);

row = 0;

for km = 1:Nm

    diffusivity = thermal_diffusivity_m2_s(km);

    conductionDelay_s = ...
        former_wall_m^2/diffusivity;

    for kr = 1:Nramp

        ramp_C_min = rampSweep_C_min(kr);

        for ktau = 1:Ntau

            row = row+1;

            tauOuter_s = ...
                tauOuterSweep_s(ktau);

            tauInner_s = ...
                tauOuter_s+conductionDelay_s;

            [t,Tlayers,dTdtLayers] = ...
                simulateRadialThermalModel( ...
                Nlayers,Tref_C,thermal_step_C, ...
                ramp_C_min,tauOuter_s,tauInner_s, ...
                dtThermal_s,Tend_s);

            shupeIntegral = ...
                shupeWeight_m2.'*dTdtLayers;

            omegaSeq_rad_s = ...
                shupeCoeff*shupeIntegral;

            omegaQAD_rad_s = ...
                winding_asymmetry_fraction*omegaSeq_rad_s;

            omegaSeq_deg_h = ...
                omegaSeq_rad_s*180/pi*3600;

            omegaQAD_deg_h = ...
                omegaQAD_rad_s*180/pi*3600;

            maxSeq = ...
                max(abs(omegaSeq_deg_h));

            maxQAD = ...
                max(abs(omegaQAD_deg_h));

            rmsQAD = ...
                sqrt(mean(omegaQAD_deg_h.^2));

            if maxSeq > 0
                requiredAsym = ...
                    100*thermal_budget_deg_h/maxSeq;
            else
                requiredAsym = Inf;
            end

            thMaterial(row) = material(km);
            thRamp(row) = ramp_C_min;
            thTauOuter(row) = tauOuter_s;
            thTauInner(row) = tauInner_s;
            thMaxSeq_deg_h(row) = maxSeq;
            thMaxQAD_deg_h(row) = maxQAD;
            thRMSQAD_deg_h(row) = rmsQAD;
            thRequiredAsymPct(row) = requiredAsym;
            thPassBudget(row) = ...
                maxQAD <= thermal_budget_deg_h;
        end
    end
end

thermalTransientResults = table( ...
    thMaterial, ...
    thRamp, ...
    thTauOuter, ...
    thTauInner, ...
    thMaxSeq_deg_h, ...
    thMaxQAD_deg_h, ...
    thRMSQAD_deg_h, ...
    thRequiredAsymPct, ...
    thPassBudget, ...
    'VariableNames', ...
    { ...
    'Former_material', ...
    'Ambient_ramp_C_per_min', ...
    'Outer_thermal_time_constant_s', ...
    'Inner_effective_time_constant_s', ...
    'Max_sequential_Shupe_deg_h', ...
    'Max_QAD2pct_proxy_deg_h', ...
    'RMS_QAD2pct_proxy_deg_h', ...
    'Max_allowed_winding_asymmetry_percent', ...
    'Pass_thermal_budget' ...
    });

writetable( ...
    thermalTransientResults, ...
    'FOG_v7_shupe_transient_sweep.csv');

%% ============================================================
% v7C - MATERIAL SCREENING
%% ============================================================

disp("")
disp("==============================================")
disp(" v7C - FORMER MATERIAL SCREENING")
disp("==============================================")

% Screening przy 1 C/min i tau_outer = 60 s.
screenRamp = 1;
screenTau = 60;

screenShupe_deg_h = zeros(Nm,1);

for km = 1:Nm

    idx = ...
        thermalTransientResults.Former_material == material(km) & ...
        thermalTransientResults.Ambient_ramp_C_per_min == screenRamp & ...
        thermalTransientResults.Outer_thermal_time_constant_s == screenTau;

    screenShupe_deg_h(km) = ...
        thermalTransientResults.Max_QAD2pct_proxy_deg_h(idx);
end

passShupe = ...
    screenShupe_deg_h <= thermal_budget_deg_h;

% Jawny stress-risk proxy:
% <=5 ppm/K mismatch to silica.
passCTEMismatch = ...
    CTE_mismatch_ppm_K <= 5;

% Czy Class A wystarcza do kompensacji scale factor przy 20 deg/s.
passScalePtA = ...
    passPtA;

allPass = ...
    passShupe & passCTEMismatch & passScalePtA;

materialScreening = table( ...
    material, ...
    CTE_1_K*1e6, ...
    CTE_mismatch_ppm_K, ...
    k_W_mK, ...
    rho_kg_m3, ...
    cp_J_kgK, ...
    thermal_diffusivity_m2_s, ...
    uniformCoeff_ppm_K, ...
    allowedSensorError_C, ...
    screenShupe_deg_h, ...
    passScalePtA, ...
    passCTEMismatch, ...
    passShupe, ...
    allPass, ...
    material_note, ...
    'VariableNames', ...
    { ...
    'Material', ...
    'CTE_ppm_K', ...
    'CTE_mismatch_to_silica_ppm_K', ...
    'Thermal_conductivity_W_mK', ...
    'Density_kg_m3', ...
    'Specific_heat_J_kgK', ...
    'Thermal_diffusivity_m2_s', ...
    'Uniform_scale_temp_coeff_ppm_K', ...
    'Allowed_temp_sensor_error_at_20deg_s_C', ...
    'Max_QAD2pct_Shupe_at_1Cmin_tau60_deg_h', ...
    'Pass_scale_with_Pt100_ClassA', ...
    'Pass_CTE_mismatch_5ppmK_proxy', ...
    'Pass_Shupe_budget', ...
    'Pass_all_screening', ...
    'Note' ...
    });

disp(materialScreening)

writetable( ...
    materialScreening, ...
    'FOG_v7_former_material_screening.csv');

idxSelected = find(allPass,1,'first');

if isempty(idxSelected)
    warning("No former material passes all v7 screening criteria.")
    idxSelected = 2; % Invar fallback for sensor study only.
end

selectedMaterial = material(idxSelected);

fprintf("\nProvisional selected former = %s\n",selectedMaterial)

%% ============================================================
% v7D - SENSOR COMPENSATION REQUIREMENTS
%% ============================================================

disp("")
disp("==============================================")
disp(" v7D - TEMPERATURE SENSOR / COMPENSATION")
disp("==============================================")

selectedIdx = idxSelected;

% Granice asymetrii bez aktywnej kompensacji dla wybranego formera.
idxFast60 = ...
    thermalTransientResults.Former_material == selectedMaterial & ...
    thermalTransientResults.Ambient_ramp_C_per_min == 5 & ...
    thermalTransientResults.Outer_thermal_time_constant_s == 60;

idxFast120 = ...
    thermalTransientResults.Former_material == selectedMaterial & ...
    thermalTransientResults.Ambient_ramp_C_per_min == 5 & ...
    thermalTransientResults.Outer_thermal_time_constant_s == 120;

maxAsymFast60_pct = ...
    thermalTransientResults.Max_allowed_winding_asymmetry_percent(idxFast60);

maxAsymFast120_pct = ...
    thermalTransientResults.Max_allowed_winding_asymmetry_percent(idxFast120);

% Stress-test compensation:
sensorRamp_C_min = 5;
sensorTauOuter_s = 60;

diffusivitySelected = ...
    thermal_diffusivity_m2_s(selectedIdx);

sensorTauInner_s = ...
    sensorTauOuter_s + ...
    former_wall_m^2/diffusivitySelected;

[tSensor,TlayersSensor,dTdtSensor] = ...
    simulateRadialThermalModel( ...
    Nlayers,Tref_C,thermal_step_C, ...
    sensorRamp_C_min, ...
    sensorTauOuter_s,sensorTauInner_s, ...
    dtThermal_s,Tend_s);

trueIntegral = ...
    shupeWeight_m2.'*dTdtSensor;

omegaTrueQAD_deg_h = ...
    winding_asymmetry_fraction * ...
    shupeCoeff*trueIntegral * ...
    180/pi*3600;

samplePeriodSweep_s = [0.5 1 2 5]';
sensorNoiseSweep_C = [0.005 0.01 0.03 0.05]';

sensorFilterTau_s = 10;
NmcSensor = 20;

Nsamp = numel(samplePeriodSweep_s);
Nnoise = numel(sensorNoiseSweep_C);

sensorRows = Nsamp*Nnoise;

sTs = zeros(sensorRows,1);
sNoise = zeros(sensorRows,1);
sRMS = zeros(sensorRows,1);
sP95 = zeros(sensorRows,1);
sMax = zeros(sensorRows,1);
sPass = false(sensorRows,1);

row = 0;

for ks = 1:Nsamp

    Tsens = samplePeriodSweep_s(ks);

    for kn = 1:Nnoise

        row = row+1;

        sigmaT = sensorNoiseSweep_C(kn);

        rmsRuns = zeros(NmcSensor,1);
        p95Runs = zeros(NmcSensor,1);
        maxRuns = zeros(NmcSensor,1);

        for irun = 1:NmcSensor

            [rmsErr,p95Err,maxErr] = ...
                evaluateTwoSensorCompensation( ...
                tSensor, ...
                TlayersSensor, ...
                omegaTrueQAD_deg_h, ...
                shupeWeight_m2, ...
                shupeCoeff, ...
                winding_asymmetry_fraction, ...
                Tsens, ...
                sigmaT, ...
                sensorFilterTau_s, ...
                2700000+1000*row+irun);

            rmsRuns(irun) = rmsErr;
            p95Runs(irun) = p95Err;
            maxRuns(irun) = maxErr;
        end

        sTs(row) = Tsens;
        sNoise(row) = sigmaT;
        sRMS(row) = mean(rmsRuns);
        sP95(row) = mean(p95Runs);
        sMax(row) = mean(maxRuns);
        sPass(row) = ...
            sP95(row) <= thermal_budget_deg_h;
    end
end

sensorCompResults = table( ...
    sTs, ...
    sNoise, ...
    repmat(sensorFilterTau_s,sensorRows,1), ...
    repmat(sensorRamp_C_min,sensorRows,1), ...
    sRMS, ...
    sP95, ...
    sMax, ...
    sPass, ...
    'VariableNames', ...
    { ...
    'Sensor_sample_period_s', ...
    'Sensor_noise_STD_C', ...
    'Compensation_filter_tau_s', ...
    'Thermal_stress_ramp_C_per_min', ...
    'Residual_RMS_deg_h', ...
    'Residual_P95_abs_deg_h', ...
    'Residual_mean_max_abs_deg_h', ...
    'Pass_thermal_budget' ...
    });

disp(sensorCompResults)

writetable( ...
    sensorCompResults, ...
    'FOG_v7_temperature_sensor_sweep.csv');

%% ============================================================
% v7E - PT100 CLASS REQUIREMENT
%% ============================================================

disp("")
disp("==============================================")
disp(" v7E - SENSOR CLASS REQUIREMENT")
disp("==============================================")

selectedAllowedError_C = ...
    allowedSensorError_C(selectedIdx);

classPassSelected = ...
    ptTolAt25_C <= selectedAllowedError_C;

sensorClassTable = table( ...
    ptClass, ...
    ptTolAt25_C, ...
    classPassSelected, ...
    'VariableNames', ...
    { ...
    'Pt100_class', ...
    'Tolerance_at_25C_C', ...
    'Pass_uniform_scale_requirement' ...
    });

disp(sensorClassTable)

writetable( ...
    sensorClassTable, ...
    'FOG_v7_pt100_class_check.csv');

%% ============================================================
% v7F - THERMAL BOM LOCK
%% ============================================================

disp("")
disp("==============================================")
disp(" v7F - THERMAL BOM / PROCESS REQUIREMENTS")
disp("==============================================")

item = [ ...
    "Coil former material"; ...
    "Coil thermal enclosure"; ...
    "Temperature sensor INNER"; ...
    "Temperature sensor OUTER"; ...
    "Temperature readout"; ...
    "Winding method"; ...
    "Fiber fixing / potting"; ...
    "Thermal characterization test" ...
    ];

status = [ ...
    "PROVISIONAL MATERIAL LOCK"; ...
    "FABRICATE / VERIFY"; ...
    "BUY / ORGANIZE"; ...
    "BUY / ORGANIZE"; ...
    "BUILD / BUY"; ...
    "PROCESS REQUIREMENT"; ...
    "OPEN - v7.1 STRESS MODEL"; ...
    "LAB TEST REQUIRED" ...
    ];

minimumRequirement = [ ...
    sprintf("%s class or material with CTE mismatch <=5 ppm/K and validated thermal response",selectedMaterial); ...
    "effective outer thermal time constant >=60 s WITH active two-sensor compensation for fast transients"; ...
    "Pt100/Pt1000 Class A or better, 4-wire preferred"; ...
    "Pt100/Pt1000 Class A or better, 4-wire preferred"; ...
    "2 channels; ~1 Hz adequate; filtered noise <=0.01 C RMS after ~10 s filtering"; ...
    sprintf("symmetric/QAD; <=2%% with active compensation; without compensation at 5 C/min require <=%.2f%% for tau60 or <=%.2f%% for tau120",maxAsymFast60_pct,maxAsymFast120_pct); ...
    "low-stress and symmetric; final material/adhesive after stress calibration"; ...
    "ambient ramps 1 and 5 C/min with simultaneous inner/outer/gyro logging" ...
    ];

preferred = [ ...
    "Invar36 benchmark if local machining/cost acceptable"; ...
    "removable insulation/enclosure; tau >=60 s with compensation; >=120 s gives extra margin but still needs compensation for 5 C/min at 2% asymmetry"; ...
    "Pt100 Class AA, 4-wire, bonded near inner former"; ...
    "Pt100 Class AA, 4-wire, bonded near outer coil/enclosure"; ...
    "precision RTD ADC; target filtered noise <=0.005 C RMS; <=0.01 C is minimum model PASS"; ...
    "true quadrupolar winding process with layer/order record"; ...
    "minimal-stress fixation; avoid rigid unknown-CTE potting before test"; ...
    "thermal chamber or controlled heater + reference thermometer" ...
    ];

why = [ ...
    "combined CTE mismatch, scale-factor and Shupe screening"; ...
    "v7 Shupe model requires slowing external transient"; ...
    "mean temperature / inner boundary for scale and gradient estimate"; ...
    "outer boundary for radial gradient / Shupe estimate"; ...
    "two-sensor compensation is limited by derivative noise"; ...
    "pure Shupe cancels for symmetric fiber pairs"; ...
    "unmodelled thermo-mechanical stress can exceed pure Shupe"; ...
    "calibrates simplified thermal model before final BOM" ...
    ];

thermalBom = table( ...
    item,status,minimumRequirement,preferred,why, ...
    'VariableNames', ...
    { ...
    'Item', ...
    'Status', ...
    'Minimum_requirement', ...
    'Preferred_requirement', ...
    'Why' ...
    });

disp(thermalBom)

writetable( ...
    thermalBom, ...
    'FOG_v7_thermal_bom.csv');

%% ============================================================
% v7G - ACCEPTANCE TESTS
%% ============================================================

test = [ ...
    "Former CTE / material certificate"; ...
    "Empty former thermal lag"; ...
    "Wound coil inner-outer lag"; ...
    "1 C/min Shupe test"; ...
    "5 C/min stress test"; ...
    "RTD absolute check"; ...
    "RTD noise check"; ...
    "Compensation replay"; ...
    "Scale factor vs temperature" ...
    ];

method = [ ...
    "supplier datasheet/certificate + dimension measurement"; ...
    "ambient step/ramp, inner/outer reference sensors"; ...
    "same test after winding 1 km SMF"; ...
    "controlled ramp with gyro at zero rate"; ...
    "controlled fast ramp, compensation enabled/disabled"; ...
    "ice point or calibrated reference thermometer"; ...
    "constant-temperature logging after filtering"; ...
    "offline apply v7 compensation to recorded temperatures"; ...
    "known rotation or equivalent calibrated phase over temperature" ...
    ];

criterion = [ ...
    "CTE class consistent with selected material; geometry documented"; ...
    "effective outer tau >=60 s target"; ...
    "model updated with measured tau_inner/tau_outer"; ...
    sprintf("thermal error <=%.3f deg/h after compensation target",thermal_budget_deg_h); ...
    "with 2% asymmetry active compensation required; target P95 residual <=0.120 deg/h; also record uncompensated response"; ...
    "Class A design minimum; AA preferred; Class B passes uniform-scale model but has less margin"; ...
    "<=0.01 C RMS minimum after chosen digital filter; <=0.005 C preferred"; ...
    sprintf("P95 residual <=%.3f deg/h target",thermal_budget_deg_h); ...
    "temperature coefficient measured and used in calibration" ...
    ];

thermalAcceptance = table( ...
    test,method,criterion, ...
    'VariableNames', ...
    { ...
    'Test', ...
    'Method', ...
    'Pass_or_output_criterion' ...
    });

writetable( ...
    thermalAcceptance, ...
    'FOG_v7_thermal_acceptance_tests.csv');

%% ============================================================
% PODSUMOWANIE
%% ============================================================

disp("")
disp("==============================================")
disp(" FOG v7 - ANALIZA TERMICZNA ZAKONCZONA")
disp("==============================================")
fprintf("thermal budget            = %.4f deg/h\n",thermal_budget_deg_h)
fprintf("selected former           = %s\n",selectedMaterial)
fprintf("selected scale coeff      = %.4f ppm/K\n", ...
    uniformCoeff_ppm_K(selectedIdx))
fprintf("allowed sensor abs error  = %.3f C @20 deg/s\n", ...
    selectedAllowedError_C)
fprintf("winding asymmetry proxy   = %.2f %%\n", ...
    100*winding_asymmetry_fraction)
fprintf("5 C/min no-comp asym max  = %.3f %% @tau60, %.3f %% @tau120\n", ...
    maxAsymFast60_pct,maxAsymFast120_pct)
disp("")
disp("Utworzono:")
disp("  FOG_v7_uniform_temperature_sweep.csv")
disp("  FOG_v7_shupe_transient_sweep.csv")
disp("  FOG_v7_former_material_screening.csv")
disp("  FOG_v7_temperature_sensor_sweep.csv")
disp("  FOG_v7_pt100_class_check.csv")
disp("  FOG_v7_thermal_bom.csv")
disp("  FOG_v7_thermal_acceptance_tests.csv")
disp("")
disp("UWAGA:")
disp("  v7 modeluje pure Shupe + uproszczony radialny transient.")
disp("  Nie modeluje jeszcze pelnego Mohr/T-dot stress effect.")
disp("  Potting/klej pozostaja celowo otwarte do v7.1.")
disp("")

%% ============================================================
% WYKRESY
%% ============================================================

figure('Name','FOG v7 - former material screening')

bar( ...
    categorical(material), ...
    [abs(uniformCoeff_ppm_K) screenShupe_deg_h])

grid on
ylabel('value')
legend('|scale temp coeff| [ppm/K]', ...
       'QAD2% Shupe @1C/min [deg/h]', ...
       'Location','best')
title('FOG v7 - thermal former tradeoff')

figure('Name','FOG v7 - sensor compensation')

goodNoise = ...
    sensorCompResults.Sensor_noise_STD_C == 0.01;

plot( ...
    sensorCompResults.Sensor_sample_period_s(goodNoise), ...
    sensorCompResults.Residual_P95_abs_deg_h(goodNoise), ...
    'o-', ...
    'LineWidth',1.5)

hold on
yline(thermal_budget_deg_h,'--')

grid on
xlabel('sensor sample period [s]')
ylabel('P95 residual thermal error [deg/h]')
title('FOG v7 - 0.01 C sensor-noise case')

%% ============================================================
% FUNKCJE
%% ============================================================

function sf = thermalScaleFactor( ...
    T,Tref,L0,D0,ng0,dngdT,alphaFiber,alphaFormer, ...
    c,lambda,fmod,phi0,K0,J1beta0)

    dT = T-Tref;

    Lt = ...
        L0*(1+alphaFiber*dT);

    Dt = ...
        D0*(1+alphaFormer*dT);

    ngt = ...
        ng0+dngdT*dT;

    taut = ...
        ngt*Lt/c;

    beta = ...
        2*phi0*abs(sin(pi*fmod*taut));

    Kt = ...
        2*pi*Lt*Dt/(lambda*c);

    sf = ...
        (Kt/K0)*besselj(1,beta)/J1beta0;
end

function [t,Tlayers,dTdtLayers] = ...
    simulateRadialThermalModel( ...
    Nlayers,T0,stepC,rampCmin,tauOuter,tauInner,dt,Tend)

    t = (0:dt:Tend);

    ramp_C_s = ...
        rampCmin/60;

    Tamb = ...
        T0 + min(ramp_C_s*t,stepC);

    depth = ...
        linspace(0,1,Nlayers)';

    tauLayer = ...
        tauOuter + ...
        depth*(tauInner-tauOuter);

    Tlayers = ...
        T0*ones(Nlayers,numel(t));

    for k = 2:numel(t)

        for il = 1:Nlayers

            Tlayers(il,k) = ...
                Tlayers(il,k-1) + ...
                dt*(Tamb(k-1)-Tlayers(il,k-1))/tauLayer(il);
        end
    end

    dTdtLayers = zeros(size(Tlayers));

    for il = 1:Nlayers
        dTdtLayers(il,:) = ...
            gradient(Tlayers(il,:),dt);
    end
end

function [rmsErr,p95Err,maxErr] = ...
    evaluateTwoSensorCompensation( ...
    t,Tlayers,omegaTrueDegH,weights,shupeCoeff,qadFraction, ...
    samplePeriod,noiseSTD,filterTau,seed)

    rng(seed);

    dt = t(2)-t(1);

    sampleStep = ...
        max(1,round(samplePeriod/dt));

    idx = ...
        1:sampleStep:numel(t);

    ts = t(idx);

    Touter = ...
        Tlayers(1,idx);

    Tinner = ...
        Tlayers(end,idx);

    Touter = ...
        Touter + noiseSTD*randn(size(Touter));

    Tinner = ...
        Tinner + noiseSTD*randn(size(Tinner));

    alphaLP = ...
        samplePeriod/(filterTau+samplePeriod);

    TouterF = Touter;
    TinnerF = Tinner;

    for k = 2:numel(ts)

        TouterF(k) = ...
            TouterF(k-1) + ...
            alphaLP*(Touter(k)-TouterF(k-1));

        TinnerF(k) = ...
            TinnerF(k-1) + ...
            alphaLP*(Tinner(k)-TinnerF(k-1));
    end

    dOuter = ...
        gradient(TouterF,samplePeriod);

    dInner = ...
        gradient(TinnerF,samplePeriod);

    Nlayers = size(Tlayers,1);

    depth = ...
        linspace(0,1,Nlayers)';

    dLayerEst = zeros(Nlayers,numel(ts));

    for il = 1:Nlayers

        dLayerEst(il,:) = ...
            (1-depth(il))*dOuter + ...
            depth(il)*dInner;
    end

    integralEst = ...
        weights.'*dLayerEst;

    omegaEstDegH = ...
        qadFraction * ...
        shupeCoeff*integralEst * ...
        180/pi*3600;

    omegaTrueSampled = ...
        interp1(t,omegaTrueDegH,ts,'linear');

    residual = ...
        omegaTrueSampled-omegaEstDegH;

    % Pomijamy start filtru.
    valid = ...
        ts >= max(30,3*filterTau);

    r = residual(valid);

    rmsErr = ...
        sqrt(mean(r.^2));

    p95Err = ...
        empiricalPercentile(abs(r),95);

    maxErr = ...
        max(abs(r));
end

function q = empiricalPercentile(x,p)

    x = sort(x(:));
    n = numel(x);

    if n == 0
        q = NaN;
        return
    end

    if n == 1
        q = x(1);
        return
    end

    pos = 1 + (n-1)*(p/100);

    i0 = floor(pos);
    i1 = ceil(pos);

    if i0 == i1
        q = x(i0);
    else
        w = pos-i0;
        q = (1-w)*x(i0)+w*x(i1);
    end
end
