%% ============================================================
% FOG_closed_loop_v8.m
% Interferometryczny zyroskop swiatlowodowy - model v8
% MATLAB / Simulink R2023b
%
% CEL:
% - sprawdzic sens i wykonalnosc closed-loop dla obecnego FOG,
% - wyznaczyc wymagania modulatora fazy i drivera,
% - policzyc serrodyne / phase-ramp requirements,
% - porownac PZT/fiber-stretcher z szybkim EO phase modulator,
% - zaprojektowac baseband PI controller,
% - wyznaczyc wymagania NCO/DAC,
% - wygenerowac BOM closed-loop i model FOG_v8.slx.
%
% WAZNE:
% v8 rozdziela dwa problemy:
%
% 1) BASEBAND LOOP:
%    residual Omega -> PI -> commanded feedback Omega.
%
% 2) PHYSICAL PHASE-RAMP ACTUATOR:
%    feedback Omega -> phase slope -> finite phase range -> reset.
%
% Model reset-bandwidth jest wymaganiem inzynierskim:
% przyjmujemy tr_10-90 ~= 0.35/BW i wymagamy,
% aby reset zajmowal <= reset_fraction okresu sawtooth.
%
% To nie jest pelny model rezonansow konkretnego PZT.
% Konkretna sztuka musi przejsc test rampy / resetu.
%% ============================================================

clc
close all
bdclose('all')

disp("==============================================")
disp(" FOG v8 - CLOSED LOOP / ACTUATOR / DAC BOM")
disp("==============================================")

%% ============================================================
% FOG - PARAMETRY ZWERYFIKOWANE
%% ============================================================

c = 299792458;
lambda = 1550e-9;

L = 1000;
D = 159.394500392266e-3;
ng = 1.4682;

K_sag = ...
    2*pi*L*D/(lambda*c);

tau = ...
    ng*L/c;

K_phase_to_deg_s = ...
    (180/pi)/K_sag;

% Wymagana szybkosc rampy fazy:
% Delta_phi_fb = slope * tau
% K_sag * Omega_rad_s + Delta_phi_fb = 0
slope_per_deg_s = ...
    K_sag*(pi/180)/tau;

wrap2pi_per_deg_s_Hz = ...
    slope_per_deg_s/(2*pi);

Omega_range_deg_s = 20;

slope_fullscale_rad_s = ...
    slope_per_deg_s*Omega_range_deg_s;

wrap2pi_fullscale_Hz = ...
    wrap2pi_per_deg_s_Hz*Omega_range_deg_s;

fprintf("K_sag                   = %.9f rad/(rad/s)\n",K_sag)
fprintf("tau                     = %.6f us\n",tau*1e6)
fprintf("phase slope / deg/s     = %.3f rad/s\n",slope_per_deg_s)
fprintf("2pi wraps / deg/s       = %.3f Hz\n",wrap2pi_per_deg_s_Hz)
fprintf("2pi wrap @20 deg/s      = %.3f kHz\n",wrap2pi_fullscale_Hz/1e3)

%% ============================================================
% v8A - ANALITYCZNE WYMAGANIA PHASE RAMP / RESET
%% ============================================================

disp("")
disp("==============================================")
disp(" v8A - PHASE RAMP / RESET REQUIREMENTS")
disp("==============================================")

reset_fraction = 0.10;

phaseCycles = [1 2 4 8]';

resetFreq_Hz = ...
    wrap2pi_fullscale_Hz./phaseCycles;

requiredActuatorBW_Hz = ...
    0.35*resetFreq_Hz/reset_fraction;

rampTable = table( ...
    phaseCycles, ...
    2*pi*phaseCycles, ...
    resetFreq_Hz/1e3, ...
    requiredActuatorBW_Hz/1e3, ...
    'VariableNames', ...
    { ...
    'Phase_span_cycles_2pi', ...
    'Phase_span_rad', ...
    'Reset_frequency_at_20deg_s_kHz', ...
    'Min_actuator_BW_for_10pct_reset_kHz' ...
    });

disp(rampTable)

writetable( ...
    rampTable, ...
    'FOG_v8_phase_ramp_requirement.csv');

%% ============================================================
% v8B - ACTUATOR CLASSES
%
% Current benchmark values:
% FPS-001: current product class.
% FPS-002: current long-range low-Vpi fiber shifter class.
% LiNbO3: generic high-speed EO phase-modulator class.
%
% These are design benchmarks, not automatic vendor selection.
%% ============================================================

disp("")
disp("==============================================")
disp(" v8B - ACTUATOR FEASIBILITY")
disp("==============================================")

actuator = [ ...
    "Fiber PZT high-Vpi class (FPS-001 benchmark)"; ...
    "Fiber PZT low-Vpi class (FPS-002 small benchmark)"; ...
    "Fast LiNbO3 EO phase-modulator class" ...
    ];

actuatorBW_Hz = [ ...
    20e3; ...
    20e3; ...
    100e6 ...
    ];

Vpi_design_V = [ ...
    20; ...
    4.5; ...
    5 ...
    ];

driverVpp_V = [ ...
    50; ...
    50; ...
    20 ...
    ];

phaseRangeSpec_pi = [ ...
    8; ...
    65; ...
    Inf ...
    ];

piezoCap_F = [ ...
    NaN; ...
    0.18e-6; ...
    NaN ...
    ];

Na = numel(actuator);

availableCyclesByVoltage = zeros(Na,1);
availableCyclesBySpec = zeros(Na,1);
usableCycles = zeros(Na,1);

resetAtFull_Hz = zeros(Na,1);
requiredBW_Hz = zeros(Na,1);
maxOmegaByReset_deg_s = zeros(Na,1);
VppUsed_V = zeros(Na,1);
rampCurrent_A = NaN(Na,1);
resetPeakCurrent_A = NaN(Na,1);
feasible20deg = false(Na,1);

for k = 1:Na

    availableCyclesByVoltage(k) = ...
        floor(driverVpp_V(k)/(2*Vpi_design_V(k)));

    if isinf(phaseRangeSpec_pi(k))
        availableCyclesBySpec(k) = Inf;
    else
        availableCyclesBySpec(k) = ...
            floor(phaseRangeSpec_pi(k)/2);
    end

    usableCycles(k) = ...
        min(availableCyclesByVoltage(k),availableCyclesBySpec(k));

    if usableCycles(k) < 1
        usableCycles(k) = 0;
        continue
    end

    resetAtFull_Hz(k) = ...
        wrap2pi_fullscale_Hz/usableCycles(k);

    requiredBW_Hz(k) = ...
        0.35*resetAtFull_Hz(k)/reset_fraction;

    maxResetFreq = ...
        reset_fraction*actuatorBW_Hz(k)/0.35;

    maxOmegaByReset_deg_s(k) = ...
        maxResetFreq*usableCycles(k)/wrap2pi_per_deg_s_Hz;

    VppUsed_V(k) = ...
        2*Vpi_design_V(k)*usableCycles(k);

    if ~isnan(piezoCap_F(k))

        rampCurrent_A(k) = ...
            piezoCap_F(k)* ...
            VppUsed_V(k)* ...
            resetAtFull_Hz(k);

        resetPeakCurrent_A(k) = ...
            rampCurrent_A(k)/reset_fraction;
    end

    feasible20deg(k) = ...
        actuatorBW_Hz(k) >= requiredBW_Hz(k) && ...
        maxOmegaByReset_deg_s(k) >= Omega_range_deg_s;
end

actuatorResults = table( ...
    actuator, ...
    actuatorBW_Hz/1e3, ...
    Vpi_design_V, ...
    driverVpp_V, ...
    usableCycles, ...
    resetAtFull_Hz/1e3, ...
    requiredBW_Hz/1e3, ...
    maxOmegaByReset_deg_s, ...
    VppUsed_V, ...
    rampCurrent_A, ...
    resetPeakCurrent_A, ...
    feasible20deg, ...
    'VariableNames', ...
    { ...
    'Actuator_class', ...
    'Actuator_BW_kHz', ...
    'Vpi_design_V', ...
    'Driver_available_Vpp', ...
    'Usable_2pi_cycles_before_reset', ...
    'Reset_frequency_at_20deg_s_kHz', ...
    'Required_BW_for_10pct_reset_kHz', ...
    'Ideal_max_Omega_by_reset_deg_s', ...
    'Used_phase_ramp_Vpp', ...
    'Capacitive_linear_ramp_current_A', ...
    'Approx_reset_peak_current_A', ...
    'Pass_20deg_s_ideal_reset_test' ...
    });

disp(actuatorResults)

writetable( ...
    actuatorResults, ...
    'FOG_v8_actuator_feasibility.csv');

%% ============================================================
% v8C - DRIVER / VPI TRADE-OFF DLA 20 kHz FIBER PZT
%% ============================================================

disp("")
disp("==============================================")
disp(" v8C - PZT DRIVER / VPI TRADEOFF")
disp("==============================================")

pztVpi_V = [2.5 4.5 10 20]';
driverSweepVpp = [20 40 50 80 100 150]';

Np = numel(pztVpi_V);
Nd = numel(driverSweepVpp);

rows = Np*Nd;

cVpi = zeros(rows,1);
cVpp = zeros(rows,1);
cCycles = zeros(rows,1);
cReset_kHz = NaN(rows,1);
cBWreq_kHz = NaN(rows,1);
cOmegaMax = zeros(rows,1);
cPass20 = false(rows,1);

row = 0;

for kp = 1:Np

    for kd = 1:Nd

        row = row+1;

        Vpi = pztVpi_V(kp);
        Vpp = driverSweepVpp(kd);

        Ncycles = ...
            floor(Vpp/(2*Vpi));

        cVpi(row) = Vpi;
        cVpp(row) = Vpp;
        cCycles(row) = Ncycles;

        if Ncycles >= 1

            fReset = ...
                wrap2pi_fullscale_Hz/Ncycles;

            bwReq = ...
                0.35*fReset/reset_fraction;

            maxFreset = ...
                reset_fraction*20e3/0.35;

            omegaMax = ...
                maxFreset*Ncycles/wrap2pi_per_deg_s_Hz;

            cReset_kHz(row) = fReset/1e3;
            cBWreq_kHz(row) = bwReq/1e3;
            cOmegaMax(row) = omegaMax;
            cPass20(row) = omegaMax>=20;
        end
    end
end

pztTrade = table( ...
    cVpi,cVpp,cCycles,cReset_kHz,cBWreq_kHz,cOmegaMax,cPass20, ...
    'VariableNames', ...
    { ...
    'Vpi_V', ...
    'Driver_Vpp', ...
    'Usable_2pi_cycles', ...
    'Reset_frequency_at_20deg_s_kHz', ...
    'Required_BW_kHz', ...
    'Ideal_max_Omega_with_20kHz_PZT_deg_s', ...
    'Pass_20deg_s' ...
    });

writetable( ...
    pztTrade, ...
    'FOG_v8_pzt_driver_tradeoff.csv');

%% ============================================================
% v8D - NCO / DAC REQUIREMENTS
%% ============================================================

disp("")
disp("==============================================")
disp(" v8D - NCO / DAC REQUIREMENTS")
disp("==============================================")

fsDAC = [0.5e6 1e6 2e6]';
accBits = [24 28 32]';

rows = numel(fsDAC)*numel(accBits);

dFs = zeros(rows,1);
dAcc = zeros(rows,1);
dOmegaLSB = zeros(rows,1);
dSamples2pi = zeros(rows,1);

row = 0;

for kf = 1:numel(fsDAC)

    for kb = 1:numel(accBits)

        row = row+1;

        dFs(row) = fsDAC(kf);
        dAcc(row) = accBits(kb);

        dOmegaLSB(row) = ...
            fsDAC(kf) / ...
            (2^accBits(kb)*wrap2pi_per_deg_s_Hz);

        dSamples2pi(row) = ...
            fsDAC(kf)/wrap2pi_fullscale_Hz;
    end
end

ncoResults = table( ...
    dFs/1e6, ...
    dAcc, ...
    dOmegaLSB, ...
    dOmegaLSB*3600, ...
    dSamples2pi, ...
    'VariableNames', ...
    { ...
    'DAC_update_MSps', ...
    'Phase_accumulator_bits', ...
    'Rate_word_LSB_deg_s', ...
    'Rate_word_LSB_deg_h', ...
    'Samples_per_optical_2pi_at_20deg_s' ...
    });

disp(ncoResults)

writetable( ...
    ncoResults, ...
    'FOG_v8_nco_requirements.csv');

dacBits = [12 14 16]';
dacSpan_Vpp = 50;
VpiForDAC = [4.5 20];

dacRows = numel(dacBits)*numel(VpiForDAC);

dbits = zeros(dacRows,1);
dVpi = zeros(dacRows,1);
dVlsb_mV = zeros(dacRows,1);
dPhaseLSB_mrad = zeros(dacRows,1);

row = 0;

for kv = 1:numel(VpiForDAC)

    for kb = 1:numel(dacBits)

        row = row+1;

        bits = dacBits(kb);
        Vpi = VpiForDAC(kv);

        Vlsb = ...
            dacSpan_Vpp/(2^bits-1);

        phaseLSB = ...
            pi*Vlsb/Vpi;

        dbits(row) = bits;
        dVpi(row) = Vpi;
        dVlsb_mV(row) = Vlsb*1e3;
        dPhaseLSB_mrad(row) = phaseLSB*1e3;
    end
end

dacResults = table( ...
    dbits,dVpi,dVlsb_mV,dPhaseLSB_mrad, ...
    'VariableNames', ...
    { ...
    'DAC_bits', ...
    'Vpi_V', ...
    'DAC_LSB_mV_for_50Vpp_span', ...
    'Optical_phase_LSB_mrad' ...
    });

writetable( ...
    dacResults, ...
    'FOG_v8_dac_quantization.csv');

%% ============================================================
% v8E - BASEBAND CLOSED-LOOP PI SWEEP
%% ============================================================

disp("")
disp("==============================================")
disp(" v8E - BASEBAND CLOSED-LOOP PI")
disp("==============================================")

fs_ctrl = 10e3;
Ts_ctrl = 1/fs_ctrl;

measurement_bw_Hz = 300;
baseband_actuator_bw_Hz = 2e3;

Kp = 0.50;
controllerBandwidthSweep_Hz = [10 30 50 100]';
stepRates_deg_s = [1 20]';

equivalent_rate_noise_sample_STD = 3e-4;

Nctrl = numel(controllerBandwidthSweep_Hz);
Nstep = numel(stepRates_deg_s);

rows = Nctrl*Nstep;

ctrlBW = zeros(rows,1);
ctrlStep = zeros(rows,1);
ctrlKi = zeros(rows,1);
ctrlSettling_ms = zeros(rows,1);
ctrlOvershoot_pct = zeros(rows,1);
ctrlResidualRMS = zeros(rows,1);
ctrlEstimateRMS = zeros(rows,1);
ctrlSaturated = false(rows,1);

Omega_controller_limit_deg_s = 25;

row = 0;

for kc = 1:Nctrl

    fcCtrl = controllerBandwidthSweep_Hz(kc);
    Ki = 2*pi*fcCtrl;

    for ks = 1:Nstep

        row = row+1;

        rate = stepRates_deg_s(ks);

        [settling,overshoot,resRMS,estRMS,saturated] = ...
            simulateClosedLoop( ...
            rate, ...
            fs_ctrl, ...
            measurement_bw_Hz, ...
            baseband_actuator_bw_Hz, ...
            Kp,Ki, ...
            Omega_controller_limit_deg_s, ...
            equivalent_rate_noise_sample_STD, ...
            2800000+100*kc+ks);

        ctrlBW(row) = fcCtrl;
        ctrlStep(row) = rate;
        ctrlKi(row) = Ki;
        ctrlSettling_ms(row) = settling*1e3;
        ctrlOvershoot_pct(row) = overshoot;
        ctrlResidualRMS(row) = resRMS;
        ctrlEstimateRMS(row) = estRMS;
        ctrlSaturated(row) = saturated;
    end
end

controllerSweep = table( ...
    ctrlBW,ctrlStep, ...
    repmat(Kp,rows,1), ...
    ctrlKi, ...
    ctrlSettling_ms, ...
    ctrlOvershoot_pct, ...
    ctrlResidualRMS, ...
    ctrlEstimateRMS, ...
    ctrlSaturated, ...
    'VariableNames', ...
    { ...
    'Controller_nominal_BW_Hz', ...
    'Omega_step_deg_s', ...
    'Kp', ...
    'Ki_per_s', ...
    'Settling_2pct_ms', ...
    'Overshoot_percent', ...
    'Residual_rate_RMS_deg_s', ...
    'Feedback_estimate_RMS_error_deg_s', ...
    'Controller_saturated' ...
    });

disp(controllerSweep)

writetable( ...
    controllerSweep, ...
    'FOG_v8_controller_sweep.csv');

% Nominal controller for generated SLX.
controller_nominal_bw_Hz = 50;
Ki_nominal = 2*pi*controller_nominal_bw_Hz;

%% ============================================================
% v8F - GENERATE SIMULINK BASEBAND CLOSED-LOOP MODEL
%% ============================================================

disp("")
disp("==============================================")
disp(" v8F - GENERATE FOG_v8.slx")
disp("==============================================")

mdl = 'FOG_v8';

if bdIsLoaded(mdl)
    close_system(mdl,0)
end

if isfile([mdl '.slx'])
    delete([mdl '.slx'])
end

new_system(mdl);
open_system(mdl);

set_param(mdl,'Location',[80 100 1450 650]);

% Discrete measurement LPF.
alpha_meas = ...
    1-exp(-2*pi*measurement_bw_Hz*Ts_ctrl);

b_meas = alpha_meas;
a_meas = [1 -(1-alpha_meas)];

% PI controller - Tustin.
Cpi = ...
    tf([Kp Ki_nominal],[1 0]);

Cpi_d = ...
    c2d(Cpi,Ts_ctrl,'tustin');

[b_pi,a_pi] = ...
    tfdata(Cpi_d,'v');

% Baseband actuator response.
alpha_act = ...
    1-exp(-2*pi*baseband_actuator_bw_Hz*Ts_ctrl);

b_act = alpha_act;
a_act = [1 -(1-alpha_act)];

Omega_step_final = 20;
Omega_step_time = 0.05;

add_block( ...
    'simulink/Sources/Step', ...
    [mdl '/Rotation Input'], ...
    'Time','Omega_step_time', ...
    'Before','0', ...
    'After','Omega_step_final', ...
    'SampleTime','Ts_ctrl', ...
    'Position',[60 100 130 140]);

add_block( ...
    'simulink/Math Operations/Sum', ...
    [mdl '/Residual Omega'], ...
    'Inputs','+-', ...
    'Position',[210 90 250 150]);

add_block( ...
    'simulink/Discrete/Discrete Transfer Fcn', ...
    [mdl '/Measurement LPF'], ...
    'Numerator','b_meas', ...
    'Denominator','a_meas', ...
    'SampleTime','Ts_ctrl', ...
    'Position',[320 90 450 150]);

add_block( ...
    'simulink/Discrete/Discrete Transfer Fcn', ...
    [mdl '/PI Controller'], ...
    'Numerator','b_pi', ...
    'Denominator','a_pi', ...
    'SampleTime','Ts_ctrl', ...
    'Position',[520 90 650 150]);

add_block( ...
    'simulink/Discontinuities/Saturation', ...
    [mdl '/Feedback Limit'], ...
    'UpperLimit','Omega_controller_limit_deg_s', ...
    'LowerLimit','-Omega_controller_limit_deg_s', ...
    'Position',[720 90 820 150]);

add_block( ...
    'simulink/Discrete/Discrete Transfer Fcn', ...
    [mdl '/Feedback Actuator Baseband'], ...
    'Numerator','b_act', ...
    'Denominator','a_act', ...
    'SampleTime','Ts_ctrl', ...
    'Position',[900 90 1060 150]);

add_block( ...
    'simulink/Math Operations/Gain', ...
    [mdl '/Phase Ramp Slope'], ...
    'Gain','-slope_per_deg_s', ...
    'Position',[1130 215 1260 265]);

add_block( ...
    'simulink/Math Operations/Gain', ...
    [mdl '/2pi Reset Frequency'], ...
    'Gain','wrap2pi_per_deg_s_Hz', ...
    'Position',[1130 310 1260 360]);

add_block( ...
    'simulink/Math Operations/Abs', ...
    [mdl '/Abs Reset Frequency'], ...
    'Position',[1300 310 1350 360]);

add_block( ...
    'simulink/Sinks/Display', ...
    [mdl '/Closed Loop Omega'], ...
    'Position',[1130 75 1240 125]);

add_block( ...
    'simulink/Sinks/To Workspace', ...
    [mdl '/Save True Omega'], ...
    'VariableName','omega_true_ts', ...
    'SaveFormat','Timeseries', ...
    'Position',[180 220 300 260]);

add_block( ...
    'simulink/Sinks/To Workspace', ...
    [mdl '/Save Residual'], ...
    'VariableName','omega_residual_ts', ...
    'SaveFormat','Timeseries', ...
    'Position',[320 220 440 260]);

add_block( ...
    'simulink/Sinks/To Workspace', ...
    [mdl '/Save Feedback'], ...
    'VariableName','omega_feedback_ts', ...
    'SaveFormat','Timeseries', ...
    'Position',[900 220 1020 260]);

add_block( ...
    'simulink/Sinks/To Workspace', ...
    [mdl '/Save Slope'], ...
    'VariableName','phase_slope_ts', ...
    'SaveFormat','Timeseries', ...
    'Position',[1300 215 1400 255]);

add_block( ...
    'simulink/Sinks/To Workspace', ...
    [mdl '/Save Reset Freq'], ...
    'VariableName','reset_frequency_ts', ...
    'SaveFormat','Timeseries', ...
    'Position',[1290 400 1410 440]);

add_line(mdl,'Rotation Input/1','Residual Omega/1','autorouting','on');
add_line(mdl,'Rotation Input/1','Save True Omega/1','autorouting','on');

add_line(mdl,'Residual Omega/1','Measurement LPF/1','autorouting','on');
add_line(mdl,'Residual Omega/1','Save Residual/1','autorouting','on');

add_line(mdl,'Measurement LPF/1','PI Controller/1','autorouting','on');
add_line(mdl,'PI Controller/1','Feedback Limit/1','autorouting','on');
add_line(mdl,'Feedback Limit/1','Feedback Actuator Baseband/1','autorouting','on');

add_line(mdl,'Feedback Actuator Baseband/1','Residual Omega/2','autorouting','on');
add_line(mdl,'Feedback Actuator Baseband/1','Closed Loop Omega/1','autorouting','on');
add_line(mdl,'Feedback Actuator Baseband/1','Save Feedback/1','autorouting','on');

add_line(mdl,'Feedback Actuator Baseband/1','Phase Ramp Slope/1','autorouting','on');
add_line(mdl,'Feedback Actuator Baseband/1','2pi Reset Frequency/1','autorouting','on');

add_line(mdl,'Phase Ramp Slope/1','Save Slope/1','autorouting','on');
add_line(mdl,'2pi Reset Frequency/1','Abs Reset Frequency/1','autorouting','on');
add_line(mdl,'Abs Reset Frequency/1','Save Reset Freq/1','autorouting','on');

set_param( ...
    mdl, ...
    'SolverType','Fixed-step', ...
    'Solver','FixedStepDiscrete', ...
    'FixedStep','Ts_ctrl', ...
    'StopTime','0.5', ...
    'ReturnWorkspaceOutputs','on');

save_system(mdl);

%% ============================================================
% v8G - NOMINAL SLX VALIDATION
%% ============================================================

out = sim(mdl);

omega_true_ts = out.get('omega_true_ts');
omega_residual_ts = out.get('omega_residual_ts');
omega_feedback_ts = out.get('omega_feedback_ts');
phase_slope_ts = out.get('phase_slope_ts');
reset_frequency_ts = out.get('reset_frequency_ts');

idx = omega_feedback_ts.Time >= 0.30;

feedbackMean = ...
    mean(omega_feedback_ts.Data(idx));

feedbackStd = ...
    std(omega_feedback_ts.Data(idx));

residualMean = ...
    mean(omega_residual_ts.Data(idx));

residualStd = ...
    std(omega_residual_ts.Data(idx));

slopeMean = ...
    mean(phase_slope_ts.Data(idx));

resetMean = ...
    mean(reset_frequency_ts.Data(idx));

simulinkBaseline = table( ...
    Omega_step_final, ...
    controller_nominal_bw_Hz, ...
    feedbackMean, ...
    feedbackStd, ...
    residualMean, ...
    residualStd, ...
    slopeMean, ...
    resetMean, ...
    'VariableNames', ...
    { ...
    'Omega_input_deg_s', ...
    'Controller_BW_Hz', ...
    'Feedback_mean_deg_s', ...
    'Feedback_STD_deg_s', ...
    'Residual_mean_deg_s', ...
    'Residual_STD_deg_s', ...
    'Phase_slope_mean_rad_s', ...
    'Ideal_2pi_reset_frequency_Hz' ...
    });

disp("")
disp("FOG v8 SIMULINK BASELINE")
disp(simulinkBaseline)

writetable( ...
    simulinkBaseline, ...
    'FOG_v8_simulink_baseline.csv');

%% ============================================================
% v8H - CLOSED-LOOP BOM
%% ============================================================

disp("")
disp("==============================================")
disp(" v8H - CLOSED-LOOP BOM")
disp("==============================================")

item = [ ...
    "Closed-loop phase actuator"; ...
    "Actuator driver"; ...
    "DAC"; ...
    "Digital phase accumulator / NCO"; ...
    "Controller update"; ...
    "Feedback range"; ...
    "Reset waveform"; ...
    "Clocking"; ...
    "Open-loop PZT fallback" ...
    ];

status = [ ...
    "DESIGN DECISION AFTER v8 VALIDATION"; ...
    "MATCH TO ACTUATOR"; ...
    "ADD TO DIGITAL BOM"; ...
    "FPGA/MCU REQUIREMENT"; ...
    "DSP REQUIREMENT"; ...
    "SYSTEM REQUIREMENT"; ...
    "LAB VALIDATION REQUIRED"; ...
    "SYSTEM REQUIREMENT"; ...
    "KEEP FOR FIRST POC" ...
    ];

minimumRequirement = [ ...
    "support phase-ramp feedback for +/-20 deg/s; actuator/reset dynamics must pass v8 feasibility"; ...
    "voltage AND transient current/slew matched to phase range, reset rate and capacitance"; ...
    ">=1 MS/s update recommended; >=14 bit waveform DAC; 16 bit preferred"; ...
    ">=28 bit accumulator minimum; 32 bit preferred for rate-word resolution"; ...
    ">=10 kHz internal update; nominal PI bandwidth around 50 Hz"; ...
    "+/-20 deg/s plus margin; controller saturation >=+/-25 deg/s"; ...
    "integer 2pi phase reset; reset glitch measured at full-scale rate"; ...
    "ADC/DAC/modulation/controller derived from common low-jitter reference"; ...
    "20 kHz dither/open-loop phase shifter remains useful even if final closed-loop uses faster actuator" ...
    ];

preferred = [ ...
    "low-Vpi long-range fiber shifter if measured reset response passes; otherwise LiNbO3 EO phase modulator"; ...
    "for 0.18 uF class fiber PZT allow several hundred mA reset transient in worst modeled case"; ...
    "16 bit, >=1 MS/s, bipolar/level-shifted output into phase driver"; ...
    "32 bit or wider DDS/NCO phase accumulator"; ...
    "50 Hz nominal closed-loop bandwidth, tunable 10-100 Hz"; ...
    "+/-25 deg/s command range"; ...
    "<=10% reset duty assumption verified experimentally"; ...
    "single master oscillator for ADC, DAC and 20 kHz modulation"; ...
    "retain open-loop mode for bring-up and fault diagnosis" ...
    ];

why = [ ...
    "phase-reset dynamics, not phase amplitude alone, sets full-scale closed-loop feasibility"; ...
    "piezo capacitance turns fast reset into a current/slew requirement"; ...
    "20 deg/s produces ~24.45 kHz optical 2pi phase rate"; ...
    "rate resolution should be much finer than 0.0001 deg/s target"; ...
    "controller is baseband and does not need MHz bandwidth"; ...
    "avoid controller saturation at specified measurement range"; ...
    "nonideal reset produces optical phase glitches and bias"; ...
    "avoid coherent timing bias between digital channels"; ...
    "closed-loop should not block first optical prototype" ...
    ];

closedLoopBom = table( ...
    item,status,minimumRequirement,preferred,why, ...
    'VariableNames', ...
    { ...
    'Item', ...
    'Status', ...
    'Minimum_requirement', ...
    'Preferred_requirement', ...
    'Why' ...
    });

disp(closedLoopBom)

writetable( ...
    closedLoopBom, ...
    'FOG_v8_closed_loop_bom.csv');

%% ============================================================
% v8I - ACCEPTANCE TESTS
%% ============================================================

test = [ ...
    "Actuator Vpi"; ...
    "Actuator phase range"; ...
    "Actuator ramp linearity"; ...
    "2pi reset glitch"; ...
    "Full-scale equivalent phase rate"; ...
    "Driver reset current"; ...
    "DAC waveform"; ...
    "Closed-loop step 1 deg/s"; ...
    "Closed-loop step 20 deg/s"; ...
    "Open/closed noise comparison" ...
    ];

method = [ ...
    "interferometric voltage sweep"; ...
    "slow voltage sweep before reset"; ...
    "command triangular/sawtooth phase and measure optical phase"; ...
    "serrodyne ramp at increasing reset frequency; observe residual/demodulated bias"; ...
    "command equivalent +/-20 deg/s feedback without mechanical rotation"; ...
    "current probe / shunt during reset"; ...
    "oscilloscope + spectrum/FFT at maximum ramp rate"; ...
    "turntable or injected calibrated Sagnac-equivalent phase"; ...
    "turntable or injected calibrated Sagnac-equivalent phase"; ...
    "same optical setup, identical averaging window" ...
    ];

criterion = [ ...
    "measured value used in v8 actuator table"; ...
    "enough usable integer 2pi cycles for selected driver voltage"; ...
    "no cycle slips in intended ramp range"; ...
    "reset residual small enough to keep closed-loop bias inside error budget"; ...
    "stable command with >=20% range margin preferred"; ...
    "driver remains within voltage/current/thermal limits"; ...
    ">=20 samples per optical 2pi phase interval; no major spurs in measurement band"; ...
    "stable settling, no sustained oscillation"; ...
    "no saturation; commanded feedback tracks full-scale"; ...
    "closed-loop must improve linearity/dynamic range without unacceptable noise penalty" ...
    ];

acceptance = table( ...
    test,method,criterion, ...
    'VariableNames', ...
    { ...
    'Test', ...
    'Method', ...
    'Pass_or_output_criterion' ...
    });

writetable( ...
    acceptance, ...
    'FOG_v8_acceptance_tests.csv');

%% ============================================================
% PODSUMOWANIE
%% ============================================================

disp("")
disp("==============================================")
disp(" FOG v8 - ANALIZA ZAKONCZONA")
disp("==============================================")
fprintf("2pi phase rate @20 deg/s = %.3f kHz\n",wrap2pi_fullscale_Hz/1e3)
fprintf("1-cycle BW requirement   = %.3f kHz\n", ...
    requiredActuatorBW_Hz(1)/1e3)
fprintf("4-cycle BW requirement   = %.3f kHz\n", ...
    requiredActuatorBW_Hz(3)/1e3)
disp("")
disp("Utworzono:")
disp("  FOG_v8_phase_ramp_requirement.csv")
disp("  FOG_v8_actuator_feasibility.csv")
disp("  FOG_v8_pzt_driver_tradeoff.csv")
disp("  FOG_v8_nco_requirements.csv")
disp("  FOG_v8_dac_quantization.csv")
disp("  FOG_v8_controller_sweep.csv")
disp("  FOG_v8_simulink_baseline.csv")
disp("  FOG_v8_closed_loop_bom.csv")
disp("  FOG_v8_acceptance_tests.csv")
disp("  FOG_v8.slx")
disp("")
disp("Interpretacja kluczowa:")
disp("  closed-loop actuator musi byc oceniany razem z:")
disp("  Vpi + phase range + driver Vpp + capacitance + reset BW.")
disp("")

open_system(mdl)

%% ============================================================
% FUNKCJE
%% ============================================================

function [settling_s,overshoot_pct,residualRMS,estimateRMS,saturated] = ...
    simulateClosedLoop( ...
    rate_deg_s,fs,bwMeas,bwAct,Kp,Ki,limit,noiseSTD,seed)

    rng(seed);

    dt = 1/fs;
    T = 0.5;

    N = round(T*fs);

    stepIdx = round(0.05*fs)+1;

    omegaTrue = zeros(N,1);
    omegaTrue(stepIdx:end) = rate_deg_s;

    alphaMeas = ...
        1-exp(-2*pi*bwMeas*dt);

    alphaAct = ...
        1-exp(-2*pi*bwAct*dt);

    meas = 0;
    integ = 0;
    feedback = 0;

    feedbackLog = zeros(N,1);
    residualLog = zeros(N,1);
    estimateError = zeros(N,1);

    saturated = false;

    for k = 1:N

        residual = ...
            omegaTrue(k)-feedback;

        measurement = ...
            residual+noiseSTD*randn();

        meas = ...
            meas+alphaMeas*(measurement-meas);

        integCandidate = ...
            integ+Ki*meas*dt;

        uUnsat = ...
            Kp*meas+integCandidate;

        u = ...
            min(max(uUnsat,-limit),limit);

        if abs(u-uUnsat)>1e-12
            saturated = true;
        end

        % Simple conditional anti-windup.
        if abs(u-uUnsat)<1e-12 || ...
           (u>=limit && meas<0) || ...
           (u<=-limit && meas>0)

            integ = integCandidate;
        end

        feedback = ...
            feedback+alphaAct*(u-feedback);

        feedbackLog(k) = feedback;
        residualLog(k) = residual;
        estimateError(k) = feedback-omegaTrue(k);
    end

    t = (0:N-1)'*dt;

    tol = max(0.02*abs(rate_deg_s),1e-6);

    settling_s = NaN;

    for k = stepIdx:N

        if all(abs(estimateError(k:end))<=tol)
            settling_s = t(k)-t(stepIdx);
            break
        end
    end

    postStep = stepIdx:N;

    if rate_deg_s ~= 0
        overshoot_pct = ...
            100*(max(feedbackLog(postStep))-rate_deg_s)/abs(rate_deg_s);
    else
        overshoot_pct = 0;
    end

    steady = ...
        t>=0.30;

    residualRMS = ...
        sqrt(mean(residualLog(steady).^2));

    estimateRMS = ...
        sqrt(mean(estimateError(steady).^2));
end
