%% ============================================================
% FOG_start_v4.m
% Interferometryczny zyroskop swiatlowodowy - model v4
% MATLAB / Simulink R2023b
%
% v4:
% - zachowuje zweryfikowana architekture v3,
% - zachowuje fizyke PZT/lock-in v2.1,
% - rozbudowuje fizyczny subsystem Photoreceiver,
% - dodaje shot noise fotopradu,
% - dodaje shot noise pradu ciemnego,
% - dodaje Johnson noise rezystora TIA,
% - dodaje prad wejściowy wzmacniacza,
% - dodaje napieciowy szum wzmacniacza jako rownowazny prad,
% - dodaje ograniczone pasmo TIA,
% - kompensuje faze i amplitude TIA w lock-in,
% - wykonuje Monte Carlo dla malych predkosci katowych.
%
% UWAGA:
% Parametry fotodiody i wzmacniacza sa NOMINALNYMI zalozeniami
% modelu v4. Nie sa jeszcze zatwierdzonym BOM-em.
%% ============================================================

clc
close all
bdclose('all')

disp("==============================================")
disp(" FOG v4 - FOTODIODA + TIA + SZUMY")
disp("==============================================")

%% ============================================================
% PRZYGOTOWANIE MODELU v3
%% ============================================================

sourceModel = 'FOG_v3';
mdl = 'FOG_v4';

if ~isfile([sourceModel '.slx'])

    if isfile('FOG_start_v3.m')
        disp("FOG_v3.slx nie istnieje. Uruchamiam FOG_start_v3.m...")
        run('FOG_start_v3.m')
        bdclose('all')
    else
        error([ ...
            "Brak FOG_v3.slx oraz FOG_start_v3.m w aktualnym folderze. " ...
            "Najpierw pobierz/uruchom v3." ...
            ])
    end
end

if isfile([mdl '.slx'])
    delete([mdl '.slx'])
end

load_system(sourceModel)
save_system(sourceModel,mdl)
close_system(sourceModel,0)
load_system(mdl)

%% ============================================================
% PARAMETRY FIZYCZNE FOG - JAK v3
%% ============================================================

c = 299792458;
lambda = 1550e-9;
L = 1000;
D = 0.160;
ng = 1.4682;

K_sag = 2*pi*L*D/(lambda*c);
tau = ng*L/c;
f_opt = 1/(2*tau);

%% ============================================================
% MODULATOR PZT
%% ============================================================

beta_target = 1.84;
f_mod = 20e3;

phi0 = beta_target / ...
    (2*abs(sin(pi*f_mod*tau)));

beta_eff = ...
    2*phi0*abs(sin(pi*f_mod*tau));

%% ============================================================
% OPTYCZNY BILANS MOCY - JAK v3
%% ============================================================

P_source_W = 1.0e-3;

K1_launch_ratio = 0.50;
K1_detector_ratio = 0.50;
IL_K1_dB = 0.20;

IL_connector_common_dB = 0.20;
IL_polarizer_dB = 0.80;
IL_depolarizer_dB = 0.30;

K2_split_ratio = 0.50;
IL_K2_dB = 0.20;

alpha_fiber_dB_km = 0.20;
IL_PZT_dB = 0.50;

N_loop_splices = 6;
IL_splice_dB = 0.05;

visibility = 1.0;

eta_K1 = 10^(-IL_K1_dB/10);
eta_conn = 10^(-IL_connector_common_dB/10);
eta_pol = 10^(-IL_polarizer_dB/10);
eta_dep = 10^(-IL_depolarizer_dB/10);

eta_K2 = 10^(-IL_K2_dB/10);

IL_coil_dB = ...
    alpha_fiber_dB_km*(L/1000);

eta_coil = 10^(-IL_coil_dB/10);
eta_PZT = 10^(-IL_PZT_dB/10);

IL_loop_splices_dB = ...
    N_loop_splices*IL_splice_dB;

eta_splices = ...
    10^(-IL_loop_splices_dB/10);

eta_loop = ...
    eta_coil*eta_PZT*eta_splices;

K_front_forward = ...
    K1_launch_ratio * eta_K1 * ...
    eta_conn * eta_pol * eta_dep;

K_sagnac_power = ...
    2*K2_split_ratio*(1-K2_split_ratio) * ...
    eta_K2^2 * eta_loop;

K_front_return = ...
    eta_dep * eta_pol * eta_conn * ...
    K1_detector_ratio * eta_K1;

Pdet_scale_W = ...
    P_source_W * ...
    K_front_forward * ...
    K_sagnac_power * ...
    K_front_return;

%% ============================================================
% PHOTORECEIVER v4 - NOMINALNE PARAMETRY
%% ============================================================

% Stale fizyczne
q_e = 1.602176634e-19;          % C
k_B = 1.380649e-23;             % J/K

% Fotodioda InGaAs - zalozenia v4
Rpd = 0.9;                      % A/W
I_dark_A = 5e-9;                % 5 nA

% TIA - zalozenia v4
Rf = 20e3;                      % Ohm
Rtia = Rf;                      % zgodnosc z v3

T_receiver_K = 300;             % K
f_tia_Hz = 200e3;               % pasmo -3 dB TIA
w_tia = 2*pi*f_tia_Hz;

% Nominalny low-noise amplifier
opamp_en_V_sqrtHz = 4e-9;       % V/sqrt(Hz)
opamp_in_A_sqrtHz = 2e-15;      % A/sqrt(Hz)

% Uproszczenie v4:
% en jest przeliczany na rownowazny prad en/Rf.
% Pelny noise-gain zależny od pojemnosci fotodiody dodamy pozniej.
opamp_en_eq_A_sqrtHz = ...
    opamp_en_V_sqrtHz/Rf;

%% ============================================================
% POLITYKA NUMERYCZNA v3.1
%% ============================================================

% FAST dla 20 kHz / Monte Carlo.
Ts_solver = 0.20e-6;
Ts_noise = Ts_solver;

% Dla dyskretnego bialego szumu:
% sigma_sample = ASD * sqrt(fs/2) = ASD/sqrt(2*Ts)
noise_sample_scale = ...
    1/sqrt(2*Ts_noise);

%% ============================================================
% SZUMY STALE FOTORECEIVERA
%% ============================================================

i_dark_shot_ASD = ...
    sqrt(2*q_e*I_dark_A);

i_johnson_ASD = ...
    sqrt(4*k_B*T_receiver_K/Rf);

i_opamp_current_ASD = ...
    opamp_in_A_sqrtHz;

i_opamp_voltage_eq_ASD = ...
    opamp_en_eq_A_sqrtHz;

sigma_dark_sample_A = ...
    i_dark_shot_ASD*noise_sample_scale;

sigma_johnson_sample_A = ...
    i_johnson_ASD*noise_sample_scale;

sigma_opamp_current_sample_A = ...
    i_opamp_current_ASD*noise_sample_scale;

sigma_opamp_voltage_sample_A = ...
    i_opamp_voltage_eq_ASD*noise_sample_scale;

%% ============================================================
% LOCK-IN + KOMPENSACJA TIA
%% ============================================================

fc_lp = 300;
lp_order = 4;
[b_lp,a_lp] = ...
    butter(lp_order,2*pi*fc_lp,'s');

J1beta = besselj(1,beta_eff);
K_ref = 1/beta_eff;

% Modul harmonicznej podstawowej po TIA.
Hmag_tia_fmod = ...
    1/sqrt(1+(f_mod/f_tia_Hz)^2);

% TIA powoduje opoznienie fazowe atan(f/fc).
tia_phase_lag_rad = ...
    atan(f_mod/f_tia_Hz);

% Referencje lock-in opozniamy o ten sam kat.
ref_delay_tia_s = ...
    tia_phase_lag_rad/(2*pi*f_mod);

% Normalizacja uwzglednia modul TIA przy f_mod.
K_norm = ...
    -1/( ...
    Pdet_scale_W * ...
    visibility * ...
    Rpd * ...
    Rf * ...
    Hmag_tia_fmod * ...
    J1beta);

K_phase_to_deg = ...
    (180/pi)/K_sag;

%% ============================================================
% SREDNIA MOC I ANALITYCZNY BUDZET SZUMOW
%% ============================================================

% Dla Omega = 0:
Pdet_avg_zero_W = ...
    Pdet_scale_W * ...
    (1 + visibility*besselj(0,beta_eff));

Iphoto_avg_A = ...
    Rpd*Pdet_avg_zero_W;

i_photo_shot_ASD = ...
    sqrt(2*q_e*Iphoto_avg_A);

i_total_ASD = sqrt( ...
    i_photo_shot_ASD^2 + ...
    i_dark_shot_ASD^2 + ...
    i_johnson_ASD^2 + ...
    i_opamp_current_ASD^2 + ...
    i_opamp_voltage_eq_ASD^2);

% Noise-equivalent bandwidth 1-rzedowego LPF TIA.
ENBW_tia_Hz = ...
    (pi/2)*f_tia_Hz;

Vn_photo_rms = ...
    i_photo_shot_ASD*Rf*sqrt(ENBW_tia_Hz);

Vn_dark_rms = ...
    i_dark_shot_ASD*Rf*sqrt(ENBW_tia_Hz);

Vn_johnson_rms = ...
    i_johnson_ASD*Rf*sqrt(ENBW_tia_Hz);

Vn_opamp_i_rms = ...
    i_opamp_current_ASD*Rf*sqrt(ENBW_tia_Hz);

Vn_opamp_en_rms = ...
    i_opamp_voltage_eq_ASD*Rf*sqrt(ENBW_tia_Hz);

Vn_total_rms = sqrt( ...
    Vn_photo_rms^2 + ...
    Vn_dark_rms^2 + ...
    Vn_johnson_rms^2 + ...
    Vn_opamp_i_rms^2 + ...
    Vn_opamp_en_rms^2);

noiseNames = [ ...
    "Photo shot"; ...
    "Dark-current shot"; ...
    "Rf Johnson"; ...
    "OpAmp current"; ...
    "OpAmp voltage equiv."; ...
    "TOTAL RSS" ...
    ];

asd_A_sqrtHz = [ ...
    i_photo_shot_ASD; ...
    i_dark_shot_ASD; ...
    i_johnson_ASD; ...
    i_opamp_current_ASD; ...
    i_opamp_voltage_eq_ASD; ...
    i_total_ASD ...
    ];

vrms_V = [ ...
    Vn_photo_rms; ...
    Vn_dark_rms; ...
    Vn_johnson_rms; ...
    Vn_opamp_i_rms; ...
    Vn_opamp_en_rms; ...
    Vn_total_rms ...
    ];

varianceShare = zeros(6,1);

varianceShare(1:5) = ...
    100*(vrms_V(1:5).^2)/(Vn_total_rms^2);

varianceShare(6) = 100;

noiseBudget = table( ...
    noiseNames, ...
    asd_A_sqrtHz*1e12, ...
    vrms_V*1e6, ...
    varianceShare, ...
    'VariableNames', ...
    { ...
    'Noise_source', ...
    'Input_ASD_pA_sqrtHz', ...
    'TIA_output_RMS_uV', ...
    'Variance_share_percent' ...
    });

writetable( ...
    noiseBudget, ...
    'FOG_v4_noise_budget.csv');

%% ============================================================
% ZMIENNE STERUJACE SZUMEM
%% ============================================================

noise_enable = 0;

seed_photo = 11001;
seed_dark = 11002;
seed_johnson = 11003;
seed_opamp_i = 11004;
seed_opamp_en = 11005;

%% ============================================================
% PRZEBUDOWA PHOTORECEIVERA
%% ============================================================

photoSub = [mdl '/Photoreceiver'];

buildPhotoreceiverV4(photoSub);

set_param( ...
    photoSub, ...
    'BackgroundColor','green', ...
    'AttributesFormatString', ...
    'InGaAs + dark current + shot noise + TIA noise + 200 kHz BW');

%% ============================================================
% KOMPENSACJA FAZY TIA W DSP
%% ============================================================

dspSub = [mdl '/Lock-In DSP'];

insertTIAPhaseCompensation(dspSub);

set_param( ...
    dspSub, ...
    'AttributesFormatString', ...
    'Mixer + TIA phase match + Butterworth LPF + asin');

%% ============================================================
% DODATKOWE LOGGery TOP LEVEL
%% ============================================================

if getSimulinkBlockHandle([mdl '/Save_TIA_Noise']) == -1

    add_block( ...
        'simulink/Sinks/To Workspace', ...
        [mdl '/Save_TIA_Noise'], ...
        'VariableName','tia_noise_ts', ...
        'SaveFormat','Timeseries', ...
        'Position',[1040 340 1160 380]);

    add_line( ...
        mdl, ...
        'Photoreceiver/2', ...
        'Save_TIA_Noise/1', ...
        'autorouting','on');
end

if getSimulinkBlockHandle([mdl '/Save_Iphoto']) == -1

    add_block( ...
        'simulink/Sinks/To Workspace', ...
        [mdl '/Save_Iphoto'], ...
        'VariableName','iphoto_ts', ...
        'SaveFormat','Timeseries', ...
        'Position',[1040 400 1160 440]);

    add_line( ...
        mdl, ...
        'Photoreceiver/3', ...
        'Save_Iphoto/1', ...
        'autorouting','on');
end

%% ============================================================
% PARAMETRY SYMULACJI
%% ============================================================

Tstop_baseline = 0.050;
Tmean_start_baseline = 0.040;

set_param( ...
    mdl, ...
    'SolverType','Fixed-step', ...
    'Solver','ode4', ...
    'FixedStep',sprintf('%.17g',Ts_solver), ...
    'StopTime',sprintf('%.17g',Tstop_baseline), ...
    'ReturnWorkspaceOutputs','on');

save_system(mdl);

%% ============================================================
% INFORMACJE
%% ============================================================

fprintf("\nPHOTORECEIVER v4 - PARAMETRY NOMINALNE\n")
fprintf("---------------------------------\n")
fprintf("Rpd                 = %.3f A/W\n",Rpd)
fprintf("I_dark              = %.3f nA\n",I_dark_A*1e9)
fprintf("Rf                  = %.1f kOhm\n",Rf/1e3)
fprintf("TIA bandwidth       = %.1f kHz\n",f_tia_Hz/1e3)
fprintf("opamp en            = %.3f nV/sqrtHz\n",opamp_en_V_sqrtHz*1e9)
fprintf("opamp in            = %.3f fA/sqrtHz\n",opamp_in_A_sqrtHz*1e15)
fprintf("temperature         = %.1f K\n",T_receiver_K)
fprintf("Ts FAST             = %.3f us\n",Ts_solver*1e6)

fprintf("\nANALITYCZNY BUDZET SZUMOW @ Omega=0\n")
fprintf("---------------------------------\n")
disp(noiseBudget)

fprintf("Pdet avg            = %.3f uW\n",Pdet_avg_zero_W*1e6)
fprintf("Iphoto avg          = %.3f uA\n",Iphoto_avg_A*1e6)
fprintf("TIA ENBW            = %.3f kHz\n",ENBW_tia_Hz/1e3)
fprintf("Vnoise RSS          = %.3f uV RMS\n",Vn_total_rms*1e6)
fprintf("TIA phase lag @20k  = %.3f deg\n",tia_phase_lag_rad*180/pi)
fprintf("Reference delay     = %.3f ns\n",ref_delay_tia_s*1e9)

%% ============================================================
% TEST 1: BASELINE BEZ SZUMU
%% ============================================================

disp("")
disp("==============================================")
disp(" TEST v4A - TOR DETERMINISTYCZNY BEZ SZUMU")
disp("==============================================")

Omega_deg_s = 1;
noise_enable = 0;

out = sim(mdl);

omega_ts = out.get('omega_est_ts');

idx = ...
    omega_ts.Time >= Tmean_start_baseline;

omega_noiseless = ...
    mean(omega_ts.Data(idx));

omega_noiseless_std = ...
    std(omega_ts.Data(idx));

fprintf("Omega zadane        = %.9f deg/s\n",Omega_deg_s)
fprintf("Omega zmierzone     = %.9f deg/s\n",omega_noiseless)
fprintf("Blad                = %.9f deg/s\n",omega_noiseless-Omega_deg_s)
fprintf("STD                 = %.9f deg/s\n",omega_noiseless_std)

%% ============================================================
% TEST 2: WALIDACJA RMS SZUMU TIA
%% ============================================================

disp("")
disp("==============================================")
disp(" TEST v4B - WALIDACJA SZUMU PHOTORECEIVERA")
disp("==============================================")

Omega_deg_s = 0;
noise_enable = 1;

seed_photo = 21001;
seed_dark = 21002;
seed_johnson = 21003;
seed_opamp_i = 21004;
seed_opamp_en = 21005;

Tstop_noise = 0.100;
Tnoise_start = 0.050;

set_param( ...
    mdl, ...
    'StopTime',sprintf('%.17g',Tstop_noise));

out = sim(mdl);

tia_noise_ts = out.get('tia_noise_ts');
iphoto_ts = out.get('iphoto_ts');

idxN = ...
    tia_noise_ts.Time >= Tnoise_start;

idxI = ...
    iphoto_ts.Time >= Tnoise_start;

Vnoise_sim_rms = ...
    std(tia_noise_ts.Data(idxN));

Iphoto_sim_avg = ...
    mean(iphoto_ts.Data(idxI));

noiseRmsErrorPct = ...
    100*(Vnoise_sim_rms-Vn_total_rms)/Vn_total_rms;

fprintf("Vnoise teoria       = %.6f uV RMS\n",Vn_total_rms*1e6)
fprintf("Vnoise symulacja    = %.6f uV RMS\n",Vnoise_sim_rms*1e6)
fprintf("Roznica             = %.3f %%\n",noiseRmsErrorPct)
fprintf("Iphoto teoria avg   = %.6f uA\n",Iphoto_avg_A*1e6)
fprintf("Iphoto sym avg      = %.6f uA\n",Iphoto_sim_avg*1e6)

receiverValidation = table( ...
    Vn_total_rms*1e6, ...
    Vnoise_sim_rms*1e6, ...
    noiseRmsErrorPct, ...
    Iphoto_avg_A*1e6, ...
    Iphoto_sim_avg*1e6, ...
    'VariableNames', ...
    { ...
    'Vnoise_teoria_uV_RMS', ...
    'Vnoise_symulacja_uV_RMS', ...
    'Blad_Vnoise_percent', ...
    'Iphoto_teoria_uA', ...
    'Iphoto_symulacja_uA' ...
    });

writetable( ...
    receiverValidation, ...
    'FOG_v4_receiver_validation.csv');

%% ============================================================
% TEST 3: MONTE CARLO MALYCH PREDKOSCI
%% ============================================================

disp("")
disp("==============================================")
disp(" TEST v4C - MONTE CARLO MALYCH PREDKOSCI")
disp("==============================================")

% Pierwsza seria jest celowo umiarkowana czasowo.
% Nmc mozna zwiekszyc po pierwszej walidacji.
Nmc = 12;

omegaLevels = [ ...
    0 ...
    1e-4 ...
    5e-4 ...
    1e-3 ...
    5e-3 ...
    1e-2 ...
    1e-1 ...
    1 ...
    ];

Nlevels = numel(omegaLevels);

Tstop_mc = 0.030;
Tmean_start_mc = 0.020;

set_param( ...
    mdl, ...
    'StopTime',sprintf('%.17g',Tstop_mc));

noise_enable = 1;

mcOmegaSet = zeros(Nlevels*Nmc,1);
mcRun = zeros(Nlevels*Nmc,1);
mcOmegaEst = zeros(Nlevels*Nmc,1);

row = 0;

for ilvl = 1:Nlevels

    Omega_deg_s = omegaLevels(ilvl);

    fprintf( ...
        "\nOmega = %.7f deg/s: ", ...
        Omega_deg_s)

    for irun = 1:Nmc

        row = row+1;

        baseSeed = ...
            100000 + 1000*ilvl + 10*irun;

        seed_photo = baseSeed+1;
        seed_dark = baseSeed+2;
        seed_johnson = baseSeed+3;
        seed_opamp_i = baseSeed+4;
        seed_opamp_en = baseSeed+5;

        out = sim(mdl);

        omega_ts = out.get('omega_est_ts');

        idxMC = ...
            omega_ts.Time >= Tmean_start_mc;

        omegaEstimate = ...
            mean(omega_ts.Data(idxMC));

        mcOmegaSet(row) = Omega_deg_s;
        mcRun(row) = irun;
        mcOmegaEst(row) = omegaEstimate;

        fprintf(".")
    end

    fprintf(" done")
end

fprintf("\n")

mcError = ...
    mcOmegaEst-mcOmegaSet;

mcRaw = table( ...
    mcOmegaSet, ...
    mcRun, ...
    mcOmegaEst, ...
    mcError, ...
    'VariableNames', ...
    { ...
    'Omega_zadane_deg_s', ...
    'Run', ...
    'Omega_zmierzone_deg_s', ...
    'Blad_deg_s' ...
    });

writetable( ...
    mcRaw, ...
    'FOG_v4_monte_carlo_raw.csv');

%% ------------------------------------------------------------
% PODSUMOWANIE MONTE CARLO
%% ------------------------------------------------------------

meanEst = zeros(Nlevels,1);
stdEst = zeros(Nlevels,1);
biasEst = zeros(Nlevels,1);
rmseEst = zeros(Nlevels,1);
snrRate = nan(Nlevels,1);

for ilvl = 1:Nlevels

    idxL = ...
        mcOmegaSet == omegaLevels(ilvl);

    vals = ...
        mcOmegaEst(idxL);

    errs = ...
        vals-omegaLevels(ilvl);

    meanEst(ilvl) = mean(vals);
    stdEst(ilvl) = std(vals);
    biasEst(ilvl) = mean(errs);
    rmseEst(ilvl) = sqrt(mean(errs.^2));

    if omegaLevels(ilvl) ~= 0 && stdEst(ilvl) > 0
        snrRate(ilvl) = ...
            abs(omegaLevels(ilvl))/stdEst(ilvl);
    end
end

zeroIdx = ...
    find(omegaLevels == 0,1);

sigmaZero = ...
    stdEst(zeroIdx);

biasZero = ...
    meanEst(zeroIdx);

threshold_1sigma = sigmaZero;
threshold_3sigma = 3*sigmaZero;

mcSummary = table( ...
    omegaLevels(:), ...
    meanEst, ...
    stdEst, ...
    biasEst, ...
    rmseEst, ...
    snrRate, ...
    'VariableNames', ...
    { ...
    'Omega_zadane_deg_s', ...
    'Mean_Omega_deg_s', ...
    'STD_Omega_deg_s', ...
    'Bias_deg_s', ...
    'RMSE_deg_s', ...
    'SNR_rate_over_STD' ...
    });

writetable( ...
    mcSummary, ...
    'FOG_v4_monte_carlo_summary.csv');

%% ============================================================
% BASELINE v4 CSV
%% ============================================================

baseline = table( ...
    omega_noiseless, ...
    omega_noiseless-Omega_deg_s, ...
    Rpd, ...
    I_dark_A*1e9, ...
    Rf/1e3, ...
    f_tia_Hz/1e3, ...
    Pdet_avg_zero_W*1e6, ...
    Iphoto_avg_A*1e6, ...
    Vn_total_rms*1e6, ...
    biasZero, ...
    sigmaZero, ...
    threshold_3sigma, ...
    'VariableNames', ...
    { ...
    'Omega_noiseless_at_1deg_s', ...
    'Noiseless_error_note_recomputed_later', ...
    'Rpd_A_W', ...
    'I_dark_nA', ...
    'Rf_kOhm', ...
    'TIA_BW_kHz', ...
    'Pdet_avg_zero_uW', ...
    'Iphoto_avg_zero_uA', ...
    'TIA_noise_theory_uV_RMS', ...
    'Zero_rate_bias_deg_s', ...
    'Zero_rate_sigma_deg_s', ...
    'Three_sigma_threshold_deg_s' ...
    });

% Poprawny blad baseline 1 deg/s.
baseline.Noiseless_error_note_recomputed_later(1) = ...
    omega_noiseless-1;

writetable( ...
    baseline, ...
    'FOG_v4_baseline.csv');

%% ============================================================
% RAPORT KONSOLI
%% ============================================================

disp("")
disp("==============================================")
disp(" MONTE CARLO - PODSUMOWANIE")
disp("==============================================")
disp(mcSummary)

fprintf("\nZERO-RATE\n")
fprintf("---------------------------------\n")
fprintf("bias zero           = %+ .9e deg/s\n",biasZero)
fprintf("sigma zero          = %.9e deg/s\n",sigmaZero)
fprintf("1-sigma threshold   = %.9e deg/s\n",threshold_1sigma)
fprintf("3-sigma threshold   = %.9e deg/s\n",threshold_3sigma)

%% ============================================================
% WYKRESY
%% ============================================================

figure('Name','FOG v4 - noise budget')

bar( ...
    categorical(noiseNames(1:5)), ...
    varianceShare(1:5))

grid on
ylabel('Udzial w wariancji [%]')
title('FOG v4 - budzet szumow fotoreceivera')

figure('Name','FOG v4 - Monte Carlo')

errorbar( ...
    omegaLevels, ...
    meanEst, ...
    stdEst, ...
    'o-', ...
    'LineWidth',1.5)

hold on

plot( ...
    omegaLevels, ...
    omegaLevels, ...
    '--', ...
    'LineWidth',1.2)

grid on
xlabel('Omega zadane [deg/s]')
ylabel('Omega est [deg/s]')
legend('mean +/- 1 sigma','idealna','Location','best')
title('FOG v4 - Monte Carlo z szumem photoreceivera')

figure('Name','FOG v4 - small-rate zoom')

errorbar( ...
    omegaLevels(1:6), ...
    meanEst(1:6), ...
    stdEst(1:6), ...
    'o-', ...
    'LineWidth',1.5)

hold on

plot( ...
    omegaLevels(1:6), ...
    omegaLevels(1:6), ...
    '--', ...
    'LineWidth',1.2)

grid on
xlabel('Omega zadane [deg/s]')
ylabel('Omega est [deg/s]')
title('FOG v4 - male predkosci katowe')

%% ============================================================
% KONIEC
%% ============================================================

set_param( ...
    mdl, ...
    'StopTime',sprintf('%.17g',Tstop_baseline));

save_system(mdl)
open_system(mdl)

disp("")
disp("==============================================")
disp(" FOG v4 - SYMULACJA ZAKONCZONA")
disp("==============================================")
disp("")
disp("Utworzono:")
disp("  FOG_v4.slx")
disp("  FOG_v4_noise_budget.csv")
disp("  FOG_v4_receiver_validation.csv")
disp("  FOG_v4_monte_carlo_raw.csv")
disp("  FOG_v4_monte_carlo_summary.csv")
disp("  FOG_v4_baseline.csv")
disp("")
disp("Na poziomie glownym nadal widoczne sa fizyczne")
disp("podsystemy. Dwuklik Photoreceiver pokazuje model szumowy.")
disp("")

%% ============================================================
% FUNKCJE
%% ============================================================

function buildPhotoreceiverV4(sub)

    Simulink.SubSystem.deleteContents(sub);

    %% Ports

    add_block( ...
        'simulink/Ports & Subsystems/In1', ...
        [sub '/P_detector'], ...
        'Port','1', ...
        'Position',[25 210 55 230]);

    add_block( ...
        'simulink/Ports & Subsystems/Out1', ...
        [sub '/V_TIA'], ...
        'Port','1', ...
        'Position',[1080 190 1110 210]);

    add_block( ...
        'simulink/Ports & Subsystems/Out1', ...
        [sub '/V_noise'], ...
        'Port','2', ...
        'Position',[1080 350 1110 370]);

    add_block( ...
        'simulink/Ports & Subsystems/Out1', ...
        [sub '/I_photo'], ...
        'Port','3', ...
        'Position',[1080 55 1110 75]);

    %% Photocurrent

    add_block( ...
        'simulink/Math Operations/Gain', ...
        [sub '/InGaAs Responsivity'], ...
        'Gain','Rpd', ...
        'Position',[100 195 220 245]);

    add_block( ...
        'simulink/Discontinuities/Saturation', ...
        [sub '/Positive Iphoto'], ...
        'UpperLimit','inf', ...
        'LowerLimit','0', ...
        'Position',[270 45 360 95]);

    %% Dark current DC

    add_block( ...
        'simulink/Sources/Constant', ...
        [sub '/Dark Current DC'], ...
        'Value','I_dark_A', ...
        'Position',[270 140 360 180]);

    add_block( ...
        'simulink/Math Operations/Sum', ...
        [sub '/Signal Current'], ...
        'Inputs','++', ...
        'Position',[440 180 480 250]);

    %% Photo shot noise - dynamic ASD = sqrt(2*q*Iphoto)

    add_block( ...
        'simulink/Math Operations/Gain', ...
        [sub '/2qI'], ...
        'Gain','2*q_e', ...
        'Position',[410 35 490 85]);

    add_block( ...
        'simulink/Math Operations/Math Function', ...
        [sub '/sqrt shot ASD'], ...
        'Operator','sqrt', ...
        'Position',[530 35 620 85]);

    add_block( ...
        'simulink/Math Operations/Gain', ...
        [sub '/ASD to sample sigma'], ...
        'Gain','noise_sample_scale', ...
        'Position',[660 35 780 85]);

    add_block( ...
        'simulink/Sources/Random Number', ...
        [sub '/Gaussian Photo'], ...
        'Mean','0', ...
        'Variance','1', ...
        'Seed','seed_photo', ...
        'SampleTime','Ts_noise', ...
        'Position',[660 105 780 145]);

    add_block( ...
        'simulink/Math Operations/Product', ...
        [sub '/Photo Shot Noise'], ...
        'Position',[830 55 880 115]);

    %% Constant noise sources

    addNoiseSource( ...
        sub,'Dark Shot Noise','Gaussian Dark', ...
        'sigma_dark_sample_A','seed_dark',[100 320]);

    addNoiseSource( ...
        sub,'Johnson Noise','Gaussian Johnson', ...
        'sigma_johnson_sample_A','seed_johnson',[100 400]);

    addNoiseSource( ...
        sub,'OpAmp Current Noise','Gaussian OpAmp I', ...
        'sigma_opamp_current_sample_A','seed_opamp_i',[100 480]);

    addNoiseSource( ...
        sub,'OpAmp Voltage Eq Noise','Gaussian OpAmp EN', ...
        'sigma_opamp_voltage_sample_A','seed_opamp_en',[100 560]);

    %% Noise sum

    add_block( ...
        'simulink/Math Operations/Sum', ...
        [sub '/Total Current Noise'], ...
        'Inputs','+++++', ...
        'Position',[910 320 950 510]);

    add_block( ...
        'simulink/Math Operations/Gain', ...
        [sub '/Noise Enable'], ...
        'Gain','noise_enable', ...
        'Position',[985 380 1060 430]);

    %% Total detector current

    add_block( ...
        'simulink/Math Operations/Sum', ...
        [sub '/Signal plus Noise'], ...
        'Inputs','++', ...
        'Position',[570 190 610 260]);

    %% TIA transfer functions

    add_block( ...
        'simulink/Continuous/Transfer Fcn', ...
        [sub '/TIA Signal and Noise'], ...
        'Numerator','Rf*w_tia', ...
        'Denominator','[1 w_tia]', ...
        'Position',[700 185 850 255]);

    add_block( ...
        'simulink/Continuous/Transfer Fcn', ...
        [sub '/TIA Noise Only'], ...
        'Numerator','Rf*w_tia', ...
        'Denominator','[1 w_tia]', ...
        'Position',[915 545 1040 605]);

    %% Connections signal path

    add_line( ...
        sub,'P_detector/1','InGaAs Responsivity/1', ...
        'autorouting','on');

    add_line( ...
        sub,'InGaAs Responsivity/1','Signal Current/1', ...
        'autorouting','on');

    add_line( ...
        sub,'Dark Current DC/1','Signal Current/2', ...
        'autorouting','on');

    add_line( ...
        sub,'Signal Current/1','Signal plus Noise/1', ...
        'autorouting','on');

    add_line( ...
        sub,'Noise Enable/1','Signal plus Noise/2', ...
        'autorouting','on');

    add_line( ...
        sub,'Signal plus Noise/1','TIA Signal and Noise/1', ...
        'autorouting','on');

    add_line( ...
        sub,'TIA Signal and Noise/1','V_TIA/1', ...
        'autorouting','on');

    %% Iphoto monitor

    add_line( ...
        sub,'InGaAs Responsivity/1','Positive Iphoto/1', ...
        'autorouting','on');

    add_line( ...
        sub,'Positive Iphoto/1','2qI/1', ...
        'autorouting','on');

    add_line( ...
        sub,'Positive Iphoto/1','I_photo/1', ...
        'autorouting','on');

    %% Photo shot

    add_line( ...
        sub,'2qI/1','sqrt shot ASD/1', ...
        'autorouting','on');

    add_line( ...
        sub,'sqrt shot ASD/1','ASD to sample sigma/1', ...
        'autorouting','on');

    add_line( ...
        sub,'ASD to sample sigma/1','Photo Shot Noise/1', ...
        'autorouting','on');

    add_line( ...
        sub,'Gaussian Photo/1','Photo Shot Noise/2', ...
        'autorouting','on');

    %% Noise components -> sum

    add_line( ...
        sub,'Photo Shot Noise/1','Total Current Noise/1', ...
        'autorouting','on');

    add_line( ...
        sub,'Dark Shot Noise/1','Total Current Noise/2', ...
        'autorouting','on');

    add_line( ...
        sub,'Johnson Noise/1','Total Current Noise/3', ...
        'autorouting','on');

    add_line( ...
        sub,'OpAmp Current Noise/1','Total Current Noise/4', ...
        'autorouting','on');

    add_line( ...
        sub,'OpAmp Voltage Eq Noise/1','Total Current Noise/5', ...
        'autorouting','on');

    add_line( ...
        sub,'Total Current Noise/1','Noise Enable/1', ...
        'autorouting','on');

    %% Noise-only monitor

    add_line( ...
        sub,'Noise Enable/1','TIA Noise Only/1', ...
        'autorouting','on');

    add_line( ...
        sub,'TIA Noise Only/1','V_noise/1', ...
        'autorouting','on');
end

function addNoiseSource(sub,outName,rngName,sigmaName,seedName,pos)

    x = pos(1);
    y = pos(2);

    add_block( ...
        'simulink/Sources/Random Number', ...
        [sub '/' rngName], ...
        'Mean','0', ...
        'Variance','1', ...
        'Seed',seedName, ...
        'SampleTime','Ts_noise', ...
        'Position',[x y x+120 y+40]);

    add_block( ...
        'simulink/Math Operations/Gain', ...
        [sub '/' outName], ...
        'Gain',sigmaName, ...
        'Position',[x+190 y-5 x+310 y+45]);

    add_line( ...
        sub, ...
        [rngName '/1'], ...
        [outName '/1'], ...
        'autorouting','on');
end

function insertTIAPhaseCompensation(sub)

    delayBlock = ...
        [sub '/TIA Phase Match'];

    if getSimulinkBlockHandle(delayBlock) ~= -1
        delete_block(delayBlock)
    end

    % Usun bezposrednie Reference -> Mixer.
    try
        delete_line( ...
            sub, ...
            'Reference/1', ...
            'LockIn Mixer/2')
    catch
        % Pozwala ponownie uruchomic skrypt na kopii modelu.
    end

    add_block( ...
        'simulink/Continuous/Transport Delay', ...
        delayBlock, ...
        'DelayTime','ref_delay_tia_s', ...
        'Position',[80 175 190 215]);

    add_line( ...
        sub, ...
        'Reference/1', ...
        'TIA Phase Match/1', ...
        'autorouting','on');

    add_line( ...
        sub, ...
        'TIA Phase Match/1', ...
        'LockIn Mixer/2', ...
        'autorouting','on');
end
