%% ============================================================
% FOG_bom_lock_v6_3.m
% Interferometryczny zyroskop swiatlowodowy - model v6.3
% MATLAB / Simulink R2023b
%
% CEL:
% - zamknac roboczy BOM czesci optycznej na podstawie v1-v6.2,
% - przeliczyc wymagania PZT / drivera,
% - zablokowac wymagania zrodla i jego tlumienia,
% - zweryfikowac tolerancje sprzegaczy 50:50,
% - zablokowac wymagania polaryzatora,
% - zaprojektowac geometrie 1 km cewki SMF,
% - rozdzielic: LAB VERIFY / BUY / FABRICATE / CONDITIONAL,
% - wygenerowac plan pomiarow odbiorczych przed zakupem i montazem.
%
% v6.3 jest etapem BOM-lock, a nie nowym zjawiskiem fizycznym.
% Dane z katalogow w tym skrypcie sa benchmarkami klas elementow,
% a nie automatycznym wyborem dostawcy.
%% ============================================================

clc
close all
bdclose('all')

disp("==============================================")
disp(" FOG v6.3 - OPTICAL BOM LOCK")
disp("==============================================")

%% ============================================================
% ZABLOKOWANE PARAMETRY FOG
%% ============================================================

c = 299792458;
lambda = 1550e-9;
L = 1000;
D_target = 0.160;
ng = 1.4682;

K_sag_target = ...
    2*pi*L*D_target/(lambda*c);

tau = ng*L/c;
f_opt = 1/(2*tau);

beta_target = 1.84;
f_mod = 20e3;

phi0_req_rad = ...
    beta_target/(2*abs(sin(pi*f_mod*tau)));

phase_pp_req_rad = ...
    2*phi0_req_rad;

phase_pp_req_pi = ...
    phase_pp_req_rad/pi;

J1beta = besselj(1,beta_target);

%% ============================================================
% v6.2 - ZABLOKOWANY DEPOLARYZATOR
%% ============================================================

lyot_L1_m = 1.70;
lyot_L2_m = 3.40;
lyot_active_PM_m = lyot_L1_m+lyot_L2_m;
lyot_purchase_PM_m = 6.0;

PM_beat_length_max_m = 5e-3;
lyot_splice_angle_deg = 45;
lyot_splice_target_error_deg = 0.5;
lyot_splice_safe_error_deg = 0.7;

lyot_effective_guard_bw_nm = 8;
lyot_min_effective_bw_nm = 5;
lyot_residual_proxy = 0.017452;

polarizer_ER_min_dB = 25;
polarizer_ER_preferred_dB = 30;
polarizer_IL_max_dB = 0.70;
polarizer_RL_min_dB = 55;
polarizer_RL_preferred_dB = 60;

%% ============================================================
% OPTYCZNY BUDZET MOCY - Z v3/v5
%% ============================================================

% Zweryfikowany wczesniej peak przy 1 mW zrodla.
Pdet_peak_per_1mW_W = 90.769514e-6;

Rpd = 0.9;
Rf = 20e3;

Vtia_peak_per_1mW = ...
    Pdet_peak_per_1mW_W*Rpd*Rf;

ADC_fullscale_V = 2.0;

% Dwa poziomy marginesu na nasycenie.
ADC_headroom10_max_V = 0.90*ADC_fullscale_V;
ADC_headroom20_max_V = 0.80*ADC_fullscale_V;

Psource_max_headroom10_mW = ...
    ADC_headroom10_max_V/Vtia_peak_per_1mW;

Psource_max_headroom20_mW = ...
    ADC_headroom20_max_V/Vtia_peak_per_1mW;

Psource_target_mW = 0.90;
Psource_preferred_range_mW = [0.8 1.0];

%% ============================================================
% v6.3A - PZT / PHASE SHIFTER
%% ============================================================

disp("")
disp("==============================================")
disp(" v6.3A - PHASE MODULATOR REQUIREMENTS")
disp("==============================================")

% Projektowy driver:
driver_preferred_Vpp = 50;
driver_min_bandwidth_Hz = 20e3;
driver_preferred_bandwidth_Hz = 30e3;

Vpi_max_for_50Vpp = ...
    (driver_preferred_Vpp/2)*pi/phi0_req_rad;

VpiSweep = [2 5 10 15 20 25]';

Vpk_req = ...
    phi0_req_rad/pi .* VpiSweep;

Vpp_req = 2*Vpk_req;

driverMargin50 = ...
    driver_preferred_Vpp./Vpp_req;

pztSweep = table( ...
    VpiSweep, ...
    Vpk_req, ...
    Vpp_req, ...
    driverMargin50, ...
    'VariableNames', ...
    { ...
    'Vpi_V', ...
    'Required_Vpk_at_20kHz_V', ...
    'Required_Vpp_at_20kHz_V', ...
    'Margin_with_50Vpp_driver_x' ...
    });

disp(pztSweep)

writetable( ...
    pztSweep, ...
    'FOG_v6_3_pzt_drive_sweep.csv');

% Driver current worst-case vs unknown piezo capacitance.
% Uzywamy Vpi=20 V jako konserwatywnego przypadku.
Vpk_design = ...
    phi0_req_rad/pi * 20;

Cpiezo_nF = [10 25 50 100 180]';
Cpiezo_F = Cpiezo_nF*1e-9;

Ipk_A = ...
    2*pi*f_mod .* Cpiezo_F .* Vpk_design;

Irms_A = Ipk_A/sqrt(2);
VA_reactive = Vpk_design.*Ipk_A/2;

pztDriverSweep = table( ...
    Cpiezo_nF, ...
    repmat(Vpk_design,numel(Cpiezo_nF),1), ...
    Ipk_A, ...
    Irms_A, ...
    VA_reactive, ...
    'VariableNames', ...
    { ...
    'Piezo_capacitance_nF', ...
    'Design_Vpk_V', ...
    'Required_Ipk_A', ...
    'Required_Irms_A', ...
    'Approx_reactive_VA' ...
    });

writetable( ...
    pztDriverSweep, ...
    'FOG_v6_3_pzt_driver_current.csv');

fprintf("Required phi0        = %.6f rad = %.4f pi\n", ...
    phi0_req_rad,phi0_req_rad/pi)
fprintf("Required phase p-p   = %.6f rad = %.4f pi\n", ...
    phase_pp_req_rad,phase_pp_req_pi)
fprintf("Max Vpi @50 Vpp      = %.3f V\n",Vpi_max_for_50Vpp)

%% ============================================================
% v6.3B - ZRODLO I TLUMIENIE
%% ============================================================

disp("")
disp("==============================================")
disp(" v6.3B - SOURCE POWER CONDITIONING")
disp("==============================================")

sourceBenchmark_mW = [0.5 0.8 1.0 1.2 2.5 22 40]';

VtiaPeak_V = ...
    Vtia_peak_per_1mW.*sourceBenchmark_mW;

attenToTarget_dB = ...
    max(0,10*log10(sourceBenchmark_mW/Psource_target_mW));

needsAttenuation = ...
    sourceBenchmark_mW > Psource_max_headroom10_mW;

sourcePowerResults = table( ...
    sourceBenchmark_mW, ...
    VtiaPeak_V, ...
    attenToTarget_dB, ...
    needsAttenuation, ...
    'VariableNames', ...
    { ...
    'Source_power_mW', ...
    'Predicted_TIA_peak_V', ...
    'Attenuation_to_0p9mW_dB', ...
    'Needs_attenuation_for_10pct_ADC_headroom' ...
    });

disp(sourcePowerResults)

writetable( ...
    sourcePowerResults, ...
    'FOG_v6_3_source_power_conditioning.csv');

fprintf("Max source @10%% headroom = %.3f mW\n", ...
    Psource_max_headroom10_mW)
fprintf("Max source @20%% headroom = %.3f mW\n", ...
    Psource_max_headroom20_mW)

%% ============================================================
% v6.3C - SPRZEGACZE K1/K2
%% ============================================================

disp("")
disp("==============================================")
disp(" v6.3C - COUPLER BALANCE")
disp("==============================================")

r = (0.40:0.01:0.60)';

% Wzgledna skala interferencji 2r(1-r) do nominalnego 0.5.
relInterferenceScale = ...
    2*r.*(1-r)/0.5;

scaleLoss_dB = ...
    -10*log10(relInterferenceScale);

couplerSweep = table( ...
    100*r, ...
    100*(1-r), ...
    relInterferenceScale, ...
    scaleLoss_dB, ...
    'VariableNames', ...
    { ...
    'Port_A_percent', ...
    'Port_B_percent', ...
    'Relative_interference_scale', ...
    'Penalty_dB' ...
    });

writetable( ...
    couplerSweep, ...
    'FOG_v6_3_coupler_ratio_sweep.csv');

idx45 = find(abs(r-0.45)<1e-12,1);
idx40 = find(abs(r-0.40)<1e-12,1);

fprintf("45/55 penalty        = %.4f dB\n",scaleLoss_dB(idx45))
fprintf("40/60 penalty        = %.4f dB\n",scaleLoss_dB(idx40))

%% ============================================================
% v6.3D - POLARYZATOR
%% ============================================================

disp("")
disp("==============================================")
disp(" v6.3D - POLARIZER REQUIREMENTS")
disp("==============================================")

ERSweep_dB = [20 23 25 27 30 33 35]';

leakage = ...
    10.^(-ERSweep_dB/10);

Vcal = ...
    (1-leakage)./(1+leakage);

visibilityPenalty_pct = ...
    100*(1-Vcal);

polarizerSweep = table( ...
    ERSweep_dB, ...
    leakage, ...
    Vcal, ...
    visibilityPenalty_pct, ...
    'VariableNames', ...
    { ...
    'Extinction_ratio_dB', ...
    'Leakage_power_ratio', ...
    'Calibrated_visibility', ...
    'Visibility_penalty_percent' ...
    });

disp(polarizerSweep)

writetable( ...
    polarizerSweep, ...
    'FOG_v6_3_polarizer_ER_sweep.csv');

%% ============================================================
% v6.3E - GEOMETRIA CEWKI 1 km SMF
%% ============================================================

disp("")
disp("==============================================")
disp(" v6.3E - 1 km SMF COIL GEOMETRY")
disp("==============================================")

fiber_length_m = 1000;

% SMF-28 Ultra class benchmark.
fiber_coating_diameter_m = 242e-6;

spool_core_diameter_m = 0.155;
spool_winding_width_m = 0.030;
packing_fill = 0.90;

turns_per_layer = ...
    floor(spool_winding_width_m*packing_fill/ ...
    fiber_coating_diameter_m);

remaining_m = fiber_length_m;
layer = 0;

layerDiameter_m = [];
layerTurns = [];
layerLength_m = [];

while remaining_m > 1e-9

    layer = layer+1;

    d_layer = ...
        spool_core_diameter_m + ...
        (2*layer-1)*fiber_coating_diameter_m;

    circumference = pi*d_layer;

    maxLayerLength = ...
        turns_per_layer*circumference;

    useLength = ...
        min(remaining_m,maxLayerLength);

    nTurns = ...
        useLength/circumference;

    layerDiameter_m(end+1,1) = d_layer;
    layerTurns(end+1,1) = nTurns;
    layerLength_m(end+1,1) = useLength;

    remaining_m = remaining_m-useLength;
end

nLayers = layer;
totalTurns = sum(layerTurns);

outerDiameter_m = ...
    spool_core_diameter_m + ...
    2*nLayers*fiber_coating_diameter_m;

lengthWeightedMeanDiameter_m = ...
    sum(layerDiameter_m.*layerLength_m)/ ...
    sum(layerLength_m);

diameterError_pct = ...
    100*(lengthWeightedMeanDiameter_m-D_target)/D_target;

K_sag_actual = ...
    2*pi*L*lengthWeightedMeanDiameter_m/(lambda*c);

K_sag_error_pct = ...
    100*(K_sag_actual-K_sag_target)/K_sag_target;

flangeDiameter_min_m = ...
    outerDiameter_m + 0.010;

coilSummary = table( ...
    fiber_length_m, ...
    fiber_coating_diameter_m*1e6, ...
    spool_core_diameter_m*1e3, ...
    spool_winding_width_m*1e3, ...
    packing_fill, ...
    turns_per_layer, ...
    nLayers, ...
    totalTurns, ...
    outerDiameter_m*1e3, ...
    lengthWeightedMeanDiameter_m*1e3, ...
    diameterError_pct, ...
    K_sag_actual, ...
    K_sag_error_pct, ...
    flangeDiameter_min_m*1e3, ...
    'VariableNames', ...
    { ...
    'Fiber_length_m', ...
    'Fiber_coating_diameter_um', ...
    'Spool_core_diameter_mm', ...
    'Winding_width_mm', ...
    'Packing_fill', ...
    'Turns_per_layer', ...
    'Layers', ...
    'Total_turns', ...
    'Outer_diameter_mm', ...
    'Length_weighted_mean_diameter_mm', ...
    'Mean_diameter_error_percent', ...
    'K_sag_rad_per_rad_s', ...
    'K_sag_error_percent', ...
    'Recommended_min_flange_diameter_mm' ...
    });

disp(coilSummary)

writetable( ...
    coilSummary, ...
    'FOG_v6_3_coil_geometry.csv');

layerTable = table( ...
    (1:nLayers)', ...
    layerDiameter_m*1e3, ...
    layerTurns, ...
    layerLength_m, ...
    cumsum(layerLength_m), ...
    'VariableNames', ...
    { ...
    'Layer', ...
    'Layer_center_diameter_mm', ...
    'Turns', ...
    'Fiber_length_in_layer_m', ...
    'Cumulative_length_m' ...
    });

writetable( ...
    layerTable, ...
    'FOG_v6_3_coil_layers.csv');

%% ============================================================
% v6.3F - OSTATECZNE WYMAGANIA BOM
%% ============================================================

disp("")
disp("==============================================")
disp(" v6.3F - OPTICAL BOM LOCK")
disp("==============================================")

item = [ ...
    "Broadband source SLD/ASE"; ...
    "Optical attenuator / VOA"; ...
    "K1 2x2 SM coupler"; ...
    "K2 2x2 SM coupler"; ...
    "In-line fiber polarizer"; ...
    "PM fiber for Lyot"; ...
    "Lyot PM splice process"; ...
    "Fiber phase shifter / PZT"; ...
    "PZT driver"; ...
    "SMF gyro coil fiber"; ...
    "Coil former"; ...
    "InGaAs photodiode"; ...
    "TIA"; ...
    "External connectors"; ...
    "Internal splices" ...
    ];

status = [ ...
    "LAB AVAILABLE - VERIFY"; ...
    "CONDITIONAL BUY"; ...
    "LAB AVAILABLE - VERIFY"; ...
    "LAB AVAILABLE - VERIFY"; ...
    "BUY / ORGANIZE"; ...
    "BUY / ORGANIZE"; ...
    "PROCESS / LAB CAPABILITY"; ...
    "BUY / ORGANIZE"; ...
    "BUY / ORGANIZE"; ...
    "BUY / ORGANIZE"; ...
    "FABRICATE"; ...
    "LAB AVAILABLE - VERIFY"; ...
    "BUILD / VERIFY"; ...
    "BUY AS NEEDED"; ...
    "PROCESS / CONSUMABLES" ...
    ];

minimumSpec = [ ...
    "1550 nm; effective smooth BW >=5 nm after optical front-end; adjustable delivered power <=1.10 mW"; ...
    "1550 nm; enough attenuation to set 0.8-1.0 mW at K1"; ...
    "2x2 SM, 50:50 +/-5%, 1550 nm, excess loss <=0.3 dB, PDL <=0.15 dB, RL/directivity >=55 dB"; ...
    "2x2 SM, 50:50 +/-5%, 1550 nm, excess loss <=0.3 dB, PDL <=0.15 dB, RL/directivity >=55 dB"; ...
    "1550 nm, ER >=25 dB, IL <=0.7 dB, RL >=55 dB"; ...
    "PANDA PM1550, beat length <=5 mm @1550 nm, >=6 m purchase length"; ...
    "L1=1.7 m, L2=3.4 m, length ratio 1:2, relative axes 45 deg, error <=+/-0.7 deg"; ...
    sprintf("1550 nm; bandwidth >=20 kHz; phase p-p >=%.2f pi; Vpi <=20 V preferred; low PDL/RAM",phase_pp_req_pi); ...
    sprintf("20 kHz sine; >=%.1f Vpp for Vpi=20 V; preferred >=50 Vpp; capacitive-load capable",2*phi0_req_rad/pi*20); ...
    "1000 m G.652.D / SMF-28 class, attenuation <=0.25 dB/km @1550 nm"; ...
    sprintf("core dia %.0f mm, winding width >=%.0f mm, flange dia >=%.0f mm; material TBD v7", ...
        spool_core_diameter_m*1e3,spool_winding_width_m*1e3,flangeDiameter_min_m*1e3); ...
    "InGaAs, responsivity >=0.8 A/W @1550 nm, linear at >=100 uW"; ...
    "Rf around 20 kOhm, bandwidth >=200 kHz, output compatible with 0..2 V ADC"; ...
    "FC/APC preferred where demountable; return loss around >=60 dB preferred"; ...
    "Fusion splice preferred; target <=0.05 dB per splice; avoid connectors inside Sagnac loop" ...
    ];

preferredSpec = [ ...
    "Measured smooth 30-50 nm class; 0.8-1.0 mW at K1; retain >=5 nm effective BW after K1/K2"; ...
    "VOA 0-20 dB if source power unknown/high"; ...
    "Wideband >=+/-40 nm around 1550; directivity >=60 dB; FC/APC or bare/spliced"; ...
    "Wideband >=+/-40 nm around 1550; directivity >=60 dB; bare/spliced in loop"; ...
    "ER >=30 dB, IL <0.7 dB, RL >=60 dB, PM-compatible output preferred"; ...
    "PM1550-XP/HP class; 1.7 m + 3.4 m active, 6 m total purchase"; ...
    "PM-aware fusion splicer / rotary alignment; target 45 deg +/-0.5 deg"; ...
    "All-fiber SM phase shifter class; IL <=0.1 dB, PDL <=0.05 dB, RL >=65 dB, RAM <=0.01 dB"; ...
    ">=50 Vpp and >=30 kHz small-signal bandwidth; current sized after measured piezo capacitance"; ...
    "SMF-28 Ultra / equivalent; coating about 242-250 um"; ...
    "155 mm core x 30 mm winding window; actual effective diameter measured after winding"; ...
    "Rpd about 0.9 A/W; dark current <=10 nA preferred"; ...
    "20 kOhm, ~200 kHz class, low input noise"; ...
    "FC/APC only at service boundaries"; ...
    "Fusion splice + protection sleeves; PM axis control on Lyot splice" ...
    ];

reason = [ ...
    "v6.2 coherence requirement + v3/v5 saturation limit"; ...
    "protect ADC/TIA when available SLD exceeds ~1.1 mW"; ...
    "v3 power budget; split imbalance <=+/-5% adds negligible power penalty"; ...
    "v3 Sagnac recombination and broadband operation"; ...
    "v6 polarization model and v6.2 Lyot launch"; ...
    "v6.2 safe depolarization design"; ...
    "v6.2 angle sweep: safe limit ~+/-0.7 deg"; ...
    "v2 physical modulation requires beta=1.84 at 20 kHz"; ...
    "derived directly from required phase amplitude and Vpi"; ...
    "v3/v6 low-cost non-PM coil hypothesis"; ...
    "keeps weighted mean diameter close to 160 mm target"; ...
    "v4 photoreceiver model"; ...
    "v4/v5 bandwidth and ADC headroom"; ...
    "reduce back-reflections"; ...
    "model assumes ~0.05 dB/splice and reciprocity" ...
    ];

benchmark = [ ...
    "Use lab SLD first; benchmark broad SLD classes only"; ...
    "generic 1550 nm VOA / fixed attenuator"; ...
    "2x2 SM fused wideband class"; ...
    "2x2 SM fused wideband class"; ...
    "OZ Optics miniature fiber polarizer class"; ...
    "PM1550-XP / PM1550-HP class"; ...
    "PM-capable fusion splicer / rotary axis alignment"; ...
    "Luna FPS-001 class benchmark"; ...
    "HV / piezo amplifier selected after Cpiezo measurement"; ...
    "Corning SMF-28 Ultra / equivalent"; ...
    "custom low-stress spool"; ...
    "lab InGaAs detector"; ...
    "custom / lab TIA"; ...
    "FC/APC"; ...
    "fusion splice" ...
    ];

bomLock = table( ...
    item, ...
    status, ...
    minimumSpec, ...
    preferredSpec, ...
    reason, ...
    benchmark, ...
    'VariableNames', ...
    { ...
    'Item', ...
    'Status', ...
    'Minimum_requirement', ...
    'Preferred_requirement', ...
    'Why', ...
    'Benchmark_class' ...
    });

disp(bomLock)

writetable( ...
    bomLock, ...
    'FOG_v6_3_bom_lock.csv');

%% ============================================================
% v6.3G - PLAN ODBIORCZY LAB
%% ============================================================

disp("")
disp("==============================================")
disp(" v6.3G - LAB ACCEPTANCE TESTS")
disp("==============================================")

testItem = [ ...
    "Source spectrum"; ...
    "Source power"; ...
    "K1 coupling ratio"; ...
    "K2 coupling ratio"; ...
    "K1/K2 spectral flatness"; ...
    "Photodiode responsivity"; ...
    "Photodiode/TIA linearity"; ...
    "PZT Vpi / phase gain"; ...
    "PZT 20 kHz response"; ...
    "Polarizer ER"; ...
    "Polarizer IL"; ...
    "Lyot splice angle"; ...
    "Lyot output DOP proxy"; ...
    "SMF coil length"; ...
    "SMF effective diameter"; ...
    "Loop insertion loss" ...
    ];

method = [ ...
    "OSA measurement at source and after front-end"; ...
    "calibrated optical power meter"; ...
    "inject source into each input, measure both outputs"; ...
    "inject source into each input, measure both outputs"; ...
    "OSA or swept source through assembled couplers"; ...
    "known optical power + current measurement"; ...
    "power sweep to expected >=100 uW detector level"; ...
    "interferometric voltage sweep at low frequency"; ...
    "lock-in amplitude vs drive at 20 kHz"; ...
    "polarizer + analyzer / power meter"; ...
    "power before/after polarizer"; ...
    "PM-axis capable splicer / post-splice axis check"; ...
    "polarimeter if available, otherwise calibrated analyzer test"; ...
    "OTDR / meter / spool certificate"; ...
    "mechanical measurement + winding layer record"; ...
    "power measurement before/after completed loop" ...
    ];

passCriteria = [ ...
    "effective BW after front-end >=5 nm; preferred smooth >=30 nm"; ...
    sprintf("%.2f to %.2f mW delivered to K1",Psource_preferred_range_mW(1),Psource_preferred_range_mW(2)); ...
    "45:55 to 55:45 at operating spectrum"; ...
    "45:55 to 55:45 at operating spectrum"; ...
    "effective output spectrum still meets >=5 nm guard"; ...
    ">=0.8 A/W @1550 nm"; ...
    "no saturation at nominal 1 mW source configuration"; ...
    sprintf("phi0 >= %.4f rad with available driver",phi0_req_rad); ...
    "beta calibrated to 1.84 at 20 kHz without instability"; ...
    ">=25 dB, preferred >=30 dB"; ...
    "<=0.7 dB"; ...
    "45 deg +/-0.5 deg target, <=+/-0.7 deg accept"; ...
    sprintf("proxy target <=%.5f; physical DOP mapping requires calibration",lyot_residual_proxy); ...
    "1000 m +/- construction allowance documented"; ...
    sprintf("length-weighted mean diameter close to %.2f mm and calibrated",D_target*1e3); ...
    "consistent with modeled splice/coupler/fiber loss budget" ...
    ];

when = [ ...
    "BEFORE buying new source"; ...
    "BEFORE full assembly"; ...
    "BEFORE accepting lab K1"; ...
    "BEFORE accepting lab K2"; ...
    "BEFORE locking source/couplers"; ...
    "BEFORE accepting lab photodiode"; ...
    "BEFORE ADC integration"; ...
    "AFTER phase shifter arrives"; ...
    "AFTER phase shifter arrives"; ...
    "AFTER polarizer arrives"; ...
    "AFTER polarizer arrives"; ...
    "DURING Lyot fabrication"; ...
    "AFTER Lyot fabrication"; ...
    "BEFORE winding / after winding record"; ...
    "AFTER winding"; ...
    "AFTER optical assembly" ...
    ];

acceptanceTests = table( ...
    testItem, ...
    method, ...
    passCriteria, ...
    when, ...
    'VariableNames', ...
    { ...
    'Test', ...
    'Method', ...
    'Pass_criterion', ...
    'When' ...
    });

writetable( ...
    acceptanceTests, ...
    'FOG_v6_3_lab_acceptance_tests.csv');

%% ============================================================
% v6.3H - PROCUREMENT LIST
%% ============================================================

% Procurement/action plan:
% wszystko poza elementami oznaczonymi jako LAB AVAILABLE - VERIFY.
% Dzięki temu lista nie gubi pozycji CONDITIONAL BUY, BUILD / VERIFY,
% BUY AS NEEDED ani PROCESS / CONSUMABLES.
needsAction = ...
    ~contains(status,"LAB AVAILABLE - VERIFY");

procurement = bomLock(needsAction,:);

writetable( ...
    procurement, ...
    'FOG_v6_3_procurement.csv');

%% ============================================================
% v6.3I - FINAL MODEL COPY
%% ============================================================

sourceModels = { ...
    'FOG_v6_2.slx', ...
    'FOG_v6_1.slx', ...
    'FOG_v6.slx' ...
    };

copied = false;

for k = 1:numel(sourceModels)

    if isfile(sourceModels{k})

        [~,srcName,~] = fileparts(sourceModels{k});

        targetModel = 'FOG_v6_3';

        if isfile([targetModel '.slx'])
            delete([targetModel '.slx'])
        end

        load_system(srcName);
        save_system(srcName,targetModel);
        close_system(srcName,0);

        copied = true;
        break
    end
end

if copied
    load_system('FOG_v6_3');
    save_system('FOG_v6_3');
    open_system('FOG_v6_3');
else
    warning("No v6/v6.1/v6.2 SLX found. BOM outputs created without FOG_v6_3.slx.")
end

%% ============================================================
% PODSUMOWANIE
%% ============================================================

disp("")
disp("==============================================")
disp(" FOG v6.3 - BOM LOCK ZAKONCZONY")
disp("==============================================")
disp("")
fprintf("PZT phi0 required       = %.4f rad\n",phi0_req_rad)
fprintf("PZT phase p-p           = %.4f pi\n",phase_pp_req_pi)
fprintf("Preferred PZT Vpi       <= 20 V\n")
fprintf("Preferred driver        >= 50 Vpp, >=30 kHz\n")
fprintf("Source target at K1     = %.1f-%.1f mW\n", ...
    Psource_preferred_range_mW(1),Psource_preferred_range_mW(2))
fprintf("Lyot                    = %.1f m + %.1f m PM\n",lyot_L1_m,lyot_L2_m)
fprintf("PM purchase             = %.1f m\n",lyot_purchase_PM_m)
fprintf("PM splice               = 45 deg +/- %.1f deg target\n", ...
    lyot_splice_target_error_deg)
fprintf("SMF coil                = %.0f m\n",fiber_length_m)
fprintf("Coil layers             = %d\n",nLayers)
fprintf("Coil turns              = %.0f\n",totalTurns)
fprintf("Effective mean diameter = %.3f mm\n", ...
    lengthWeightedMeanDiameter_m*1e3)
fprintf("Polarizer               >=%d dB ER, preferred >=%d dB\n", ...
    polarizer_ER_min_dB,polarizer_ER_preferred_dB)
disp("")
disp("Utworzono:")
disp("  FOG_v6_3_pzt_drive_sweep.csv")
disp("  FOG_v6_3_pzt_driver_current.csv")
disp("  FOG_v6_3_source_power_conditioning.csv")
disp("  FOG_v6_3_coupler_ratio_sweep.csv")
disp("  FOG_v6_3_polarizer_ER_sweep.csv")
disp("  FOG_v6_3_coil_geometry.csv")
disp("  FOG_v6_3_coil_layers.csv")
disp("  FOG_v6_3_bom_lock.csv")
disp("  FOG_v6_3_lab_acceptance_tests.csv")
disp("  FOG_v6_3_procurement.csv")
disp("  FOG_v6_3.slx (jesli model v6.x byl dostepny)")
disp("")
disp("Najpierw wykonaj audyt elementow z laboratorium.")
disp("Nie kupuj nowego SLD, sprzegaczy ani fotodiody przed ich pomiarem.")
disp("")
