%% ============================================================
% FOG_stress_v7_1.m
% Interferometryczny zyroskop swiatlowodowy - model v7.1
% MATLAB R2023b
%
% CEL:
% - rozdzielic pure Shupe od stress-induced T-dot / Mohr effect,
% - sprawdzic, czy provisional Invar36 nadal ma sens,
% - wyznaczyc dopuszczalny transfer odksztalcen termicznych,
% - wyznaczyc wymaganie na symetrie par uzwojenia,
% - zablokowac proces nawijania i tension-control,
% - okreslic, czego NIE wolno jeszcze zamykac w pottingu bez pomiaru,
% - wygenerowac thermo-mechanical BOM + acceptance plan.
%
% MODEL:
% Korzystamy z rozdzielenia:
%
% Omega_E = pure Shupe term + Mohr/T-dot term
%
% Dla jednorodnego T-dot i stalej roznicy wspolczynnika
% termo-optyczno-odksztalceniowego miedzy para symetryczna:
%
% Omega_M = ng*L/(4D) * Delta(n*S) * Tdot
%
% gdzie w tym modelu wrazliwosciowym:
%
% Delta(n*S) =
% n_eff*(1-p_e) * pair_mismatch * strain_transfer
% * (alpha_structure-alpha_fiber)
%
% strain_transfer = 0 ... 1 jest EFEKTYWNYM parametrem transferu
% odksztalcen. Nie jest on bezposrednio Young modulus ani nazwa kleju.
%
% v7.1 nie zastepuje FEM ani pomiaru Rayleigh-OFDR.
% Ma podac wymagania procesowe i zakres bezpiecznej konstrukcji.
%% ============================================================

clc
close all

disp("==============================================")
disp(" FOG v7.1 - THERMO-MECHANICAL STRESS / T-DOT")
disp("==============================================")

%% ============================================================
% PARAMETRY FOG / BUDZETY
%% ============================================================

L = 1000;
D = 159.394500392266e-3;

n_eff = 1.4445;
n_g = 1.4682;

alpha_fiber = 0.55e-6;

% Efektywny strain-optic coefficient silica.
% Benchmark engineering value.
p_e = 0.22;

target_rate_deg_s = 1e-4;
target_rate_deg_h = target_rate_deg_s*3600;

thermal_budget_deg_h = target_rate_deg_h/3;     % 0.12 deg/h

% Po v7 okolo polowy thermal budget zostawiamy na
% residual pure-Shupe / sensor compensation, a polowe na stress T-dot.
stress_budget_deg_h = thermal_budget_deg_h/2;   % 0.06 deg/h

ramp_design_C_min = 5;
Tdot_design_C_s = ramp_design_C_min/60;

% Acceptance slope dla liniowego stress T-dot modelu.
K_Tdot_max_deg_h_per_C_min = ...
    stress_budget_deg_h/ramp_design_C_min;

%% ============================================================
% MATERIALY FORMERA - JAK v7
%% ============================================================

material = [ ...
    "Al6061-T6"; ...
    "Invar36"; ...
    "G10-FR4"; ...
    "POM-C"; ...
    "FusedSilica benchmark" ...
    ];

alpha_structure = [ ...
    23.6e-6; ...
    1.30e-6; ...
    9.0e-6; ...
    110e-6; ...
    0.55e-6 ...
    ];

Nm = numel(material);

CTE_mismatch = ...
    abs(alpha_structure-alpha_fiber);

%% ============================================================
% SCENARIUSZE TRANSFERU NAPREZEN
%
% Nazwy sa scenariuszami projektowymi, NIE charakterystyka
% konkretnego kleju bez pomiaru.
%% ============================================================

transferName = [ ...
    "minimal/slip-like"; ...
    "compliant sparse"; ...
    "moderate bonded"; ...
    "strong bonded"; ...
    "rigid transfer" ...
    ];

strainTransfer = [ ...
    0.02; ...
    0.05; ...
    0.10; ...
    0.30; ...
    0.70 ...
    ];

pairMismatchSweep = [ ...
    0.005; ...
    0.010; ...
    0.020; ...
    0.050 ...
    ];

rampSweep_C_min = [1;5];

%% ============================================================
% v7.1A - STRESS T-DOT SWEEP
%% ============================================================

disp("")
disp("==============================================")
disp(" v7.1A - MOHR / T-DOT STRESS SWEEP")
disp("==============================================")

Nrows = ...
    Nm*numel(strainTransfer)* ...
    numel(pairMismatchSweep)* ...
    numel(rampSweep_C_min);

outMaterial = strings(Nrows,1);
outTransferName = strings(Nrows,1);
outEta = zeros(Nrows,1);
outMismatch = zeros(Nrows,1);
outRamp = zeros(Nrows,1);
outDeltaAlpha = zeros(Nrows,1);
outDeltaNS = zeros(Nrows,1);
outOmegaDegH = zeros(Nrows,1);
outKTdot = zeros(Nrows,1);
outPass = false(Nrows,1);

row = 0;

for km = 1:Nm

    for ke = 1:numel(strainTransfer)

        eta = strainTransfer(ke);

        for kp = 1:numel(pairMismatchSweep)

            mismatch = pairMismatchSweep(kp);

            for kr = 1:numel(rampSweep_C_min)

                row = row+1;

                ramp_C_min = ...
                    rampSweep_C_min(kr);

                Tdot_C_s = ...
                    ramp_C_min/60;

                deltaAlphaEff = ...
                    mismatch*eta* ...
                    (alpha_structure(km)-alpha_fiber);

                deltaNS = ...
                    n_eff*(1-p_e)*deltaAlphaEff;

                omega_rad_s = ...
                    n_g*L/(4*D) * ...
                    deltaNS*Tdot_C_s;

                omega_deg_h = ...
                    omega_rad_s*180/pi*3600;

                outMaterial(row) = material(km);
                outTransferName(row) = transferName(ke);
                outEta(row) = eta;
                outMismatch(row) = mismatch;
                outRamp(row) = ramp_C_min;
                outDeltaAlpha(row) = deltaAlphaEff*1e6;
                outDeltaNS(row) = deltaNS*1e6;
                outOmegaDegH(row) = omega_deg_h;
                outKTdot(row) = omega_deg_h/ramp_C_min;
                outPass(row) = ...
                    abs(omega_deg_h) <= stress_budget_deg_h;
            end
        end
    end
end

stressSweep = table( ...
    outMaterial, ...
    outTransferName, ...
    outEta, ...
    100*outMismatch, ...
    outRamp, ...
    outDeltaAlpha, ...
    outDeltaNS, ...
    outOmegaDegH, ...
    outKTdot, ...
    outPass, ...
    'VariableNames', ...
    { ...
    'Former_material', ...
    'Stress_transfer_scenario', ...
    'Effective_strain_transfer', ...
    'Paired_stress_mismatch_percent', ...
    'Temperature_ramp_C_per_min', ...
    'Delta_alpha_effective_ppm_K', ...
    'Delta_nS_ppm_K', ...
    'Mohr_Tdot_rate_error_deg_h', ...
    'K_Tdot_deg_h_per_C_min', ...
    'Pass_stress_budget' ...
    });

writetable( ...
    stressSweep, ...
    'FOG_v7_1_mohr_stress_sweep.csv');

%% ============================================================
% v7.1B - GRANICZNY TRANSFER I SYMETRIA
%% ============================================================

disp("")
disp("==============================================")
disp(" v7.1B - REQUIRED STRESS TRANSFER / SYMMETRY")
disp("==============================================")

designPairMismatch = 0.02;

etaMax = zeros(Nm,1);
mismatchMaxAtEta005 = zeros(Nm,1);
mismatchMaxAtEta010 = zeros(Nm,1);

for km = 1:Nm

    deltaAlpha = ...
        abs(alpha_structure(km)-alpha_fiber);

    base = ...
        n_g*L/(4*D) * ...
        n_eff*(1-p_e) * ...
        deltaAlpha*Tdot_design_C_s;

    if base == 0

        etaMax(km) = Inf;
        mismatchMaxAtEta005(km) = Inf;
        mismatchMaxAtEta010(km) = Inf;

    else

        budget_rad_s = ...
            stress_budget_deg_h/3600*pi/180;

        etaMax(km) = ...
            budget_rad_s/(base*designPairMismatch);

        mismatchMaxAtEta005(km) = ...
            budget_rad_s/(base*0.05);

        mismatchMaxAtEta010(km) = ...
            budget_rad_s/(base*0.10);
    end
end

requirementByFormer = table( ...
    material, ...
    CTE_mismatch*1e6, ...
    100*designPairMismatch*ones(Nm,1), ...
    etaMax, ...
    100*mismatchMaxAtEta005, ...
    100*mismatchMaxAtEta010, ...
    'VariableNames', ...
    { ...
    'Former_material', ...
    'CTE_mismatch_to_silica_ppm_K', ...
    'Design_pair_mismatch_percent', ...
    'Max_effective_strain_transfer_at_5Cmin', ...
    'Max_pair_mismatch_percent_if_eta_0p05', ...
    'Max_pair_mismatch_percent_if_eta_0p10' ...
    });

disp(requirementByFormer)

writetable( ...
    requirementByFormer, ...
    'FOG_v7_1_former_stress_requirement.csv');

%% ============================================================
% v7.1C - WYBRANY INVAR: TRANSFER SCENARIOS
%% ============================================================

disp("")
disp("==============================================")
disp(" v7.1C - INVAR FIXATION SCENARIOS")
disp("==============================================")

idxInvar = find(material=="Invar36",1);

invarEta = strainTransfer;
invarError5 = zeros(size(invarEta));
invarKTdot = zeros(size(invarEta));

for k = 1:numel(invarEta)

    invarError5(k) = mohrRateDegH( ...
        n_g,n_eff,p_e,L,D, ...
        alpha_structure(idxInvar),alpha_fiber, ...
        invarEta(k),designPairMismatch, ...
        ramp_design_C_min);

    invarKTdot(k) = ...
        invarError5(k)/ramp_design_C_min;
end

invarFixation = table( ...
    transferName, ...
    invarEta, ...
    100*designPairMismatch*ones(size(invarEta)), ...
    invarError5, ...
    invarKTdot, ...
    abs(invarError5)<=stress_budget_deg_h, ...
    'VariableNames', ...
    { ...
    'Scenario', ...
    'Effective_strain_transfer', ...
    'Pair_mismatch_percent', ...
    'Stress_Tdot_error_at_5Cmin_deg_h', ...
    'K_Tdot_deg_h_per_C_min', ...
    'Pass_stress_budget' ...
    });

disp(invarFixation)

writetable( ...
    invarFixation, ...
    'FOG_v7_1_invar_fixation_scenarios.csv');

%% ============================================================
% v7.1D - EFEKTYWNY CTE SRODOWISKA WIAZANIA
%% ============================================================

disp("")
disp("==============================================")
disp(" v7.1D - BONDED ENVIRONMENT CTE SWEEP")
disp("==============================================")

% Nie sa to konkretne kleje.
% To analiza: jaka roznica CTE moze byc przenoszona na fiber.
bondedCTE_ppm_K = [0.5 1 2 5 10 20 50 100]';

etaBondDesign = 0.05;
pairMismatchBond = 0.02;

Nb = numel(bondedCTE_ppm_K);

bondError = zeros(Nb,1);
bondKTdot = zeros(Nb,1);

for k = 1:Nb

    alphaBond = bondedCTE_ppm_K(k)*1e-6;

    bondError(k) = mohrRateDegH( ...
        n_g,n_eff,p_e,L,D, ...
        alphaBond,alpha_fiber, ...
        etaBondDesign,pairMismatchBond, ...
        ramp_design_C_min);

    bondKTdot(k) = ...
        bondError(k)/ramp_design_C_min;
end

maxDeltaAlphaAtBondDesign = ...
    maxAllowedCTEMismatch( ...
    n_g,n_eff,p_e,L,D, ...
    etaBondDesign,pairMismatchBond, ...
    ramp_design_C_min,stress_budget_deg_h);

bondCTESweep = table( ...
    bondedCTE_ppm_K, ...
    repmat(etaBondDesign,Nb,1), ...
    repmat(100*pairMismatchBond,Nb,1), ...
    bondError, ...
    bondKTdot, ...
    abs(bondError)<=stress_budget_deg_h, ...
    'VariableNames', ...
    { ...
    'Effective_bonded_environment_CTE_ppm_K', ...
    'Effective_strain_transfer', ...
    'Pair_mismatch_percent', ...
    'Stress_Tdot_error_at_5Cmin_deg_h', ...
    'K_Tdot_deg_h_per_C_min', ...
    'Pass_stress_budget' ...
    });

disp(bondCTESweep)

writetable( ...
    bondCTESweep, ...
    'FOG_v7_1_bonded_CTE_sweep.csv');

fprintf( ...
    "Max transferred CTE mismatch @eta=0.05, mismatch=2%% = %.3f ppm/K\n", ...
    maxDeltaAlphaAtBondDesign*1e6)

%% ============================================================
% v7.1E - WINDING TENSION
%% ============================================================

disp("")
disp("==============================================")
disp(" v7.1E - WINDING TENSION PROCESS")
disp("==============================================")

fiberGlassDiameter_m = 125e-6;
fiberGlassArea_m2 = ...
    pi*(fiberGlassDiameter_m/2)^2;

E_silica_Pa = 72e9;
g0 = 9.80665;

tension_g = [5 7.5 10 15 20]';

force_N = ...
    tension_g/1000*g0;

fiberStress_MPa = ...
    force_N/fiberGlassArea_m2/1e6;

fiberStrain_ue = ...
    force_N/(E_silica_Pa*fiberGlassArea_m2)*1e6;

tensionTable = table( ...
    tension_g, ...
    force_N, ...
    fiberStress_MPa, ...
    fiberStrain_ue, ...
    tension_g>=5 & tension_g<=10, ...
    'VariableNames', ...
    { ...
    'Winding_tension_g', ...
    'Force_N', ...
    'Glass_axial_stress_MPa', ...
    'Glass_axial_strain_microstrain', ...
    'Inside_5_to_10g_process_target' ...
    });

disp(tensionTable)

writetable( ...
    tensionTable, ...
    'FOG_v7_1_winding_tension.csv');

tensionControlTarget_g = [5 10];
tensionDynamicError_g = 0.5;

strainVariation_ue_at_0p5g = ...
    (0.5/1000*g0)/(E_silica_Pa*fiberGlassArea_m2)*1e6;

%% ============================================================
% v7.1F - DESIGN DECISION / BOM
%% ============================================================

disp("")
disp("==============================================")
disp(" v7.1F - THERMO-MECHANICAL BOM LOCK")
disp("==============================================")

% Invar eta limit przy 2% pair mismatch.
etaMaxInvar = etaMax(idxInvar);

item = [ ...
    "Coil former"; ...
    "Fiber winding pattern"; ...
    "Winding tension"; ...
    "Tension control"; ...
    "Fiber fixation"; ...
    "Full potting"; ...
    "Thermal stress acceptance"; ...
    "Strain calibration"; ...
    "Temperature compensation" ...
    ];

status = [ ...
    "PROVISIONAL LOCK"; ...
    "PROCESS LOCK"; ...
    "PROCESS LOCK"; ...
    "PROCESS REQUIREMENT"; ...
    "PROVISIONAL PROCESS"; ...
    "DO NOT LOCK BEFORE TEST"; ...
    "LAB TEST REQUIRED"; ...
    "LAB / OPTIONAL ADVANCED"; ...
    "REQUIRED" ...
    ];

minimumRequirement = [ ...
    "Invar36 class pending v7.1 physical calibration; retain Al6061 as comparison prototype if practical"; ...
    "true symmetric / quadrupolar winding with layer-order record"; ...
    "5-10 g winding tension target"; ...
    "+/-0.5 g dynamic control or better; log tension during winding"; ...
    sprintf("effective strain-transfer target <=%.3f for 2%% paired stress mismatch @5 C/min",min(0.05,etaMaxInvar)); ...
    "avoid rigid full potting until K_Tdot is measured on test coupon/coil"; ...
    sprintf("|K_Tdot| <= %.4f deg/h per (C/min) after pure-Shupe compensation",K_Tdot_max_deg_h_per_C_min); ...
    "prefer strain mapping / OFDR if available; otherwise infer K_Tdot from thermal ramp"; ...
    "retain INNER/OUTER RTD compensation from v7" ...
    ];

preferred = [ ...
    "Invar36 former for first build; compare with Al former only if machining availability/cost strongly favors Al"; ...
    "quadrupolar winding; symmetric tails and documented layer starts/stops"; ...
    "5-10 g with constant low tension; avoid high-tension winding"; ...
    "active tension control; <=+/-0.5 g benchmark"; ...
    "minimal / sparse compliant fixation first; maximize symmetry; allow slip where mechanically safe"; ...
    "only after measured stress transfer proves compliant enough"; ...
    "measure at 1 and 5 C/min, both heating and cooling"; ...
    "Rayleigh-OFDR strain-vs-temperature map if equipment exists"; ...
    "2x RTD, ~1 Hz, filtered noise <=0.005 C RMS preferred" ...
    ];

why = [ ...
    "v7 combined screening + v7.1 stress sensitivity"; ...
    "symmetry reduces both pure Shupe and stress T-dot terms"; ...
    "commercial precision FOG winding commonly uses small controlled tension"; ...
    "tension variation creates strain asymmetry even when mean tension is acceptable"; ...
    "v7.1 shows stress transfer can consume thermal budget"; ...
    "adhesive thermo-mechanical properties strongly affect thermal drift"; ...
    "direct measurable construction-level requirement"; ...
    "Mohr error depends on local strain field versus temperature"; ...
    "fast thermal ramps require active compensation in v7" ...
    ];

stressBom = table( ...
    item,status,minimumRequirement,preferred,why, ...
    'VariableNames', ...
    { ...
    'Item', ...
    'Status', ...
    'Minimum_requirement', ...
    'Preferred_requirement', ...
    'Why' ...
    });

disp(stressBom)

writetable( ...
    stressBom, ...
    'FOG_v7_1_thermomechanical_bom.csv');

%% ============================================================
% v7.1G - ACCEPTANCE PLAN
%% ============================================================

test = [ ...
    "Winding tension calibration"; ...
    "Tension stability log"; ...
    "Heating ramp K_Tdot"; ...
    "Cooling ramp K_Tdot"; ...
    "Pure-Shupe compensated residual"; ...
    "Former comparison coupon"; ...
    "Fixation comparison coupon"; ...
    "Potting decision gate"; ...
    "Optional strain map" ...
    ];

method = [ ...
    "calibrated gram-force / load-cell check before winding"; ...
    "record tension continuously during all 1000 m winding"; ...
    "5 C/min chamber/heater ramp; two RTDs; zero-rate FOG"; ...
    "-5 C/min equivalent cooling ramp; two RTDs; zero-rate FOG"; ...
    "subtract/model v7 pure-Shupe component and fit residual vs mean T-dot"; ...
    "same short fiber coupon / partial coil on Invar and Al"; ...
    "compare minimal fixation vs candidate adhesive on identical coupons"; ...
    "only approve potting if measured K_Tdot remains within stress budget"; ...
    "Rayleigh-OFDR or equivalent distributed strain-vs-temperature measurement" ...
    ];

criterion = [ ...
    "5-10 g setpoint range documented"; ...
    "+/-0.5 g dynamic variation target; excursions documented"; ...
    sprintf("|K_Tdot| <= %.4f deg/h per (C/min)",K_Tdot_max_deg_h_per_C_min); ...
    sprintf("|K_Tdot| <= %.4f deg/h per (C/min) and no large hysteresis",K_Tdot_max_deg_h_per_C_min); ...
    sprintf("stress contribution <= %.3f deg/h at 5 C/min",stress_budget_deg_h); ...
    "use measured result to confirm final former"; ...
    "choose lower K_Tdot / hysteresis / bias-spike configuration"; ...
    "PASS only after thermal-cycle and debonding/hysteresis check"; ...
    "use measured strain profile to update Delta(nS) model" ...
    ];

acceptance = table( ...
    test,method,criterion, ...
    'VariableNames', ...
    { ...
    'Test', ...
    'Method', ...
    'Pass_or_output_criterion' ...
    });

writetable( ...
    acceptance, ...
    'FOG_v7_1_acceptance_tests.csv');

%% ============================================================
% PODSUMOWANIE
%% ============================================================

disp("")
disp("==============================================")
disp(" FOG v7.1 - ANALIZA ZAKONCZONA")
disp("==============================================")
fprintf("thermal total budget       = %.3f deg/h\n",thermal_budget_deg_h)
fprintf("stress sub-budget          = %.3f deg/h\n",stress_budget_deg_h)
fprintf("K_Tdot acceptance          = %.4f deg/h/(C/min)\n", ...
    K_Tdot_max_deg_h_per_C_min)
fprintf("Invar eta max @2%% mismatch = %.4f\n",etaMaxInvar)
fprintf("preferred fixation eta     <= %.4f\n",min(0.05,etaMaxInvar))
fprintf("winding tension            = %.1f-%.1f g\n", ...
    tensionControlTarget_g(1),tensionControlTarget_g(2))
fprintf("tension dynamic target     = +/-%.1f g\n",tensionDynamicError_g)
fprintf("0.5 g strain variation     = %.2f microstrain\n", ...
    strainVariation_ue_at_0p5g)
disp("")
disp("Utworzono:")
disp("  FOG_v7_1_mohr_stress_sweep.csv")
disp("  FOG_v7_1_former_stress_requirement.csv")
disp("  FOG_v7_1_invar_fixation_scenarios.csv")
disp("  FOG_v7_1_bonded_CTE_sweep.csv")
disp("  FOG_v7_1_winding_tension.csv")
disp("  FOG_v7_1_thermomechanical_bom.csv")
disp("  FOG_v7_1_acceptance_tests.csv")
disp("")
disp("UWAGA:")
disp("  strain_transfer jest parametrem efektywnym.")
disp("  Nie wolno przypisywac konkretnego kleju do eta bez pomiaru.")
disp("  Finalny potting lock wymaga thermal-ramp calibration.")
disp("")

%% ============================================================
% WYKRESY
%% ============================================================

figure('Name','FOG v7.1 - Invar fixation')

bar( ...
    categorical(transferName), ...
    abs(invarError5))

hold on
yline(stress_budget_deg_h,'--')

grid on
ylabel('|stress T-dot error| [deg/h] @5 C/min')
title('FOG v7.1 - Invar effective strain transfer')

figure('Name','FOG v7.1 - former eta requirement')

bar( ...
    categorical(material), ...
    min(etaMax,1))

grid on
ylabel('max effective strain transfer')
title('FOG v7.1 - allowable stress transfer @2% mismatch, 5 C/min')

%% ============================================================
% FUNKCJE
%% ============================================================

function omega_deg_h = mohrRateDegH( ...
    ng,ne,pe,L,D,alphaStructure,alphaFiber,eta,mismatch,rampCmin)

    deltaAlpha = ...
        mismatch*eta*(alphaStructure-alphaFiber);

    deltaNS = ...
        ne*(1-pe)*deltaAlpha;

    Tdot = ...
        rampCmin/60;

    omega_rad_s = ...
        ng*L/(4*D)*deltaNS*Tdot;

    omega_deg_h = ...
        omega_rad_s*180/pi*3600;
end

function maxMismatch = maxAllowedCTEMismatch( ...
    ng,ne,pe,L,D,eta,mismatch,rampCmin,budgetDegH)

    budgetRadS = ...
        budgetDegH/3600*pi/180;

    Tdot = rampCmin/60;

    denom = ...
        ng*L/(4*D)*ne*(1-pe)*eta*mismatch*Tdot;

    if denom == 0
        maxMismatch = Inf;
    else
        maxMismatch = budgetRadS/abs(denom);
    end
end
