%% ============================================================
% FOG_start_v6.m
% Interferometryczny zyroskop swiatlowodowy - model v6
% MATLAB / Simulink R2023b
%
% v6:
% - zachowuje zweryfikowany tor optyczny, odbiornik i DSP v5.1,
% - pozostawia cewke 1 km jako zwykle SMF,
% - dodaje jawny model zmian stanu polaryzacji,
% - uwzglednia skonczony extinction ratio polaryzatora,
% - dodaje fenomenologiczny model depolaryzatora,
% - zmienia visibility i dodaje polarization phase bias,
% - wykonuje sweep skutecznosci depolaryzacji,
% - wykonuje Monte Carlo losowych stanow SMF.
%
% WAZNE:
% v6 jest modelem wrazliwosciowym. Parametry depolaryzacji oraz
% sprzezenia fazowego NIE sa jeszcze parametrami konkretnego BOM-u.
% Musza byc pozniej skalibrowane pomiarem lub kartami katalogowymi.
%% ============================================================

clc
close all
bdclose('all')

disp("==============================================")
disp(" FOG v6 - SMF + POLARYZACJA + DEPOLARYZATOR")
disp("==============================================")

%% ============================================================
% MODEL BAZOWY
%% ============================================================

if isfile('FOG_v5_1.slx')
    sourceModel = 'FOG_v5_1';
elseif isfile('FOG_v5.slx')
    sourceModel = 'FOG_v5';
else
    error([ ...
        "Brak FOG_v5_1.slx oraz FOG_v5.slx. " ...
        "Najpierw uruchom zweryfikowany model v5/v5.1." ...
        ])
end

mdl = 'FOG_v6';

if isfile([mdl '.slx'])
    delete([mdl '.slx'])
end

load_system(sourceModel)
save_system(sourceModel,mdl)
close_system(sourceModel,0)
load_system(mdl)

%% ============================================================
% PARAMETRY FIZYCZNE FOG
%% ============================================================

c = 299792458;
lambda = 1550e-9;
L = 1000;
D = 0.160;
ng = 1.4682;

K_sag = 2*pi*L*D/(lambda*c);
tau = ng*L/c;
f_opt = 1/(2*tau);

beta_target = 1.84;
f_mod = 20e3;

phi0 = ...
    beta_target/(2*abs(sin(pi*f_mod*tau)));

beta_eff = ...
    2*phi0*abs(sin(pi*f_mod*tau));

J1beta = besselj(1,beta_eff);
K_ref = 1/beta_eff;
K_phase_to_deg = (180/pi)/K_sag;

%% ============================================================
% OPTYKA / BUDZET MOCY - JAK v5
%% ============================================================

P_source_W = 1.0e-3;

K1_launch_ratio = 0.50;
K1_detector_ratio = 0.50;
IL_K1_dB = 0.20;

IL_connector_common_dB = 0.20;
IL_polarizer_dB = 0.80;
IL_depolarizer_dB = 0.30;

K2_split_ratio = 0.50;
IL_K2_dB = 0.20;

alpha_fiber_dB_km = 0.20;
IL_PZT_dB = 0.50;

N_loop_splices = 6;
IL_splice_dB = 0.05;

visibility = 1.0;

eta_K1 = 10^(-IL_K1_dB/10);
eta_conn = 10^(-IL_connector_common_dB/10);
eta_pol = 10^(-IL_polarizer_dB/10);
eta_dep = 10^(-IL_depolarizer_dB/10);
eta_K2 = 10^(-IL_K2_dB/10);

IL_coil_dB = alpha_fiber_dB_km*(L/1000);
eta_coil = 10^(-IL_coil_dB/10);
eta_PZT = 10^(-IL_PZT_dB/10);

IL_loop_splices_dB = ...
    N_loop_splices*IL_splice_dB;

eta_splices = ...
    10^(-IL_loop_splices_dB/10);

eta_loop = ...
    eta_coil*eta_PZT*eta_splices;

K_front_forward = ...
    K1_launch_ratio * eta_K1 * ...
    eta_conn * eta_pol * eta_dep;

K_sagnac_power = ...
    2*K2_split_ratio*(1-K2_split_ratio) * ...
    eta_K2^2 * eta_loop;

K_front_return = ...
    eta_dep * eta_pol * eta_conn * ...
    K1_detector_ratio * eta_K1;

Pdet_scale_W = ...
    P_source_W * ...
    K_front_forward * ...
    K_sagnac_power * ...
    K_front_return;

%% ============================================================
% PHOTORECEIVER - JAK v5
%% ============================================================

q_e = 1.602176634e-19;
k_B = 1.380649e-23;

Rpd = 0.9;
I_dark_A = 5e-9;

Rf = 20e3;
Rtia = Rf;

T_receiver_K = 300;

f_tia_Hz = 200e3;
w_tia = 2*pi*f_tia_Hz;

opamp_en_V_sqrtHz = 4e-9;
opamp_in_A_sqrtHz = 2e-15;
opamp_en_eq_A_sqrtHz = ...
    opamp_en_V_sqrtHz/Rf;

Pdet_avg_zero_W = ...
    Pdet_scale_W * ...
    (1 + besselj(0,beta_eff));

Iphoto_avg_A = ...
    Rpd*Pdet_avg_zero_W;

i_photo_shot_ASD = ...
    sqrt(2*q_e*Iphoto_avg_A);

i_dark_shot_ASD = ...
    sqrt(2*q_e*I_dark_A);

i_johnson_ASD = ...
    sqrt(4*k_B*T_receiver_K/Rf);

i_opamp_current_ASD = ...
    opamp_in_A_sqrtHz;

i_opamp_voltage_eq_ASD = ...
    opamp_en_eq_A_sqrtHz;

%% ============================================================
% ADC / DSP - WYNIK ROBOCZY v5.1
%% ============================================================

Vadc_min = 0.0;
Vadc_max = 2.0;
Vadc_fs = Vadc_max-Vadc_min;

adc_bits = 16;
fs_adc = 1e6;
Ts_adc = 1/fs_adc;
adc_sample_offset_s = 0;

% Po v5.1 przyjmujemy 100 kHz jako roboczy kandydat.
aa_order = 4;
f_aa_Hz = 100e3;

fc_digital_lp = 300;
digital_lp_order = 4;

q_adc = Vadc_fs/(2^adc_bits-1);

%% ============================================================
% MODEL POLARYZACJI v6
%% ============================================================

% Polaryzator:
% ER to nominalne zalozenie modelowe, jeszcze nie BOM.
polarizer_ER_dB = 25;
polarizer_leakage = 10^(-polarizer_ER_dB/10);

% Konserwatywna skala widzialnosci po polaryzatorze.
% DSP jest kalibrowany do tej wartosci.
V_cal = ...
    (1-polarizer_leakage)/(1+polarizer_leakage);

% Wlaczenie efektu polaryzacyjnego.
pol_enable = 1;

% depol_residual:
%   1.0 -> brak tlumienia wrazliwosci polaryzacyjnej,
%   0.0 -> idealne stlumienie efektu przez depolaryzator,
%   0.1 -> nominalny punkt badawczy v6.
%
% To parametr fenomenologiczny, NIE bezposrednio DOP z katalogu.
depol_residual = 0.10;

% Jones-equivalent disturbance:
% theta = wzgledne sprzezenie osi polaryzacji
% delta = wzgledna faza dwulamnosci
pol_theta0_rad = 15*pi/180;
pol_theta_amp_rad = 20*pi/180;

pol_delta0_rad = 0.20;
pol_delta_amp_rad = 0.30;

% Przyspieszone czestotliwosci zaburzen tylko do symulacji.
% Nie sa modelem widma termicznego prawdziwej cewki.
pol_theta_freq_Hz = 17;
pol_delta_freq_Hz = 23;
pol_delta_phase_rad = pi/5;

% Tylko mala czesc fazy overlap jest traktowana jako
% nieodwracalny polarization phase bias.
% Parametr musi zostac skalibrowany eksperymentalnie.
pol_nr_scale = 2.0e-4;

%% ============================================================
% KONFIGURACJA TIA + AAF + DIGITAL LPF
%% ============================================================

[b_aa,a_aa] = ...
    butter(aa_order,2*pi*f_aa_Hz,'s');

H_aa_fmod = ...
    polyval(b_aa,1j*2*pi*f_mod) / ...
    polyval(a_aa,1j*2*pi*f_mod);

H_tia_fmod = ...
    1/(1+1j*f_mod/f_tia_Hz);

H_analog_fmod = ...
    H_tia_fmod*H_aa_fmod;

Hmag_analog_fmod = ...
    abs(H_analog_fmod);

analog_phase_lag_rad = ...
    -angle(H_analog_fmod);

ref_delay_total_s = ...
    analog_phase_lag_rad/(2*pi*f_mod);

K_norm_digital = ...
    -1/( ...
    Pdet_scale_W * ...
    V_cal * ...
    Rpd * ...
    Rf * ...
    Hmag_analog_fmod * ...
    J1beta);

[b_dlp,a_dlp] = ...
    butter( ...
    digital_lp_order, ...
    fc_digital_lp/(fs_adc/2));

[sos_d,g_d] = tf2sos(b_dlp,a_dlp);
sos_d(1,1:3) = g_d*sos_d(1,1:3);

%% ============================================================
% POLITYKA NUMERYCZNA / SZUMY
%% ============================================================

Ts_solver = 0.10e-6;
Ts_noise = Ts_solver;

noise_enable = 0;

seed_photo = 150001;
seed_dark = 150002;
seed_johnson = 150003;
seed_opamp_i = 150004;
seed_opamp_en = 150005;

updateNoiseSampling();

%% ============================================================
% PRZEBUDOWA SAGNAC INTERFEROMETER
%% ============================================================

sagnacSub = [mdl '/Sagnac Interferometer'];

% Najpierw odpinamy wszystkie polaczenia top-level zwiazane z portami
% Sagnac, aby uniknac wiszacych linii po deleteContents().
try
    delete_line(mdl,'Optical Front End/1','Sagnac Interferometer/1');
catch
end

try
    delete_line(mdl,'Rotation Input/1','Sagnac Interferometer/2');
catch
end

try
    delete_line(mdl,'Sagnac Interferometer/1','Optical Front End/2');
catch
end

try
    delete_line(mdl,'Sagnac Interferometer/2','Digital Lock-In DSP/2');
catch
end

buildSagnacV6(sagnacSub);

set_param( ...
    sagnacSub, ...
    'AttributesFormatString', ...
    'K2 + 1 km standard SMF + PZT + polarization');

%% ============================================================
% PONOWNE POLACZENIA TOP-LEVEL
%% ============================================================

add_line( ...
    mdl,'Optical Front End/1','Sagnac Interferometer/1', ...
    'autorouting','on');

add_line( ...
    mdl,'Rotation Input/1','Sagnac Interferometer/2', ...
    'autorouting','on');

add_line( ...
    mdl,'Sagnac Interferometer/1','Optical Front End/2', ...
    'autorouting','on');

add_line( ...
    mdl,'Sagnac Interferometer/2','Digital Lock-In DSP/2', ...
    'autorouting','on');

%% ============================================================
% LOGOWANIE POLARYZACJI
%% ============================================================

if getSimulinkBlockHandle([mdl '/Save_Vpol']) ~= -1
    delete_block([mdl '/Save_Vpol'])
end

if getSimulinkBlockHandle([mdl '/Save_PhiPol']) ~= -1
    delete_block([mdl '/Save_PhiPol'])
end

add_block( ...
    'simulink/Sinks/To Workspace', ...
    [mdl '/Save_Vpol'], ...
    'VariableName','vpol_ts', ...
    'SaveFormat','Timeseries', ...
    'Position',[820 430 930 470]);

add_block( ...
    'simulink/Sinks/To Workspace', ...
    [mdl '/Save_PhiPol'], ...
    'VariableName','phipol_ts', ...
    'SaveFormat','Timeseries', ...
    'Position',[820 500 930 540]);

add_line( ...
    mdl,'Sagnac Interferometer/3','Save_Vpol/1', ...
    'autorouting','on');

add_line( ...
    mdl,'Sagnac Interferometer/4','Save_PhiPol/1', ...
    'autorouting','on');

%% ============================================================
% ADC / DSP - WYMUSZENIE KONFIGURACJI v6
%% ============================================================

set_param( ...
    [mdl '/ADC AFE/Sample and Hold'], ...
    'SampleTime','[Ts_adc adc_sample_offset_s]');

set_param( ...
    [mdl '/Digital Lock-In DSP/Reference Sampler'], ...
    'SampleTime','[Ts_adc adc_sample_offset_s]');

%% ============================================================
% TEST TOPOLOGII
%% ============================================================

lhSag = get_param(sagnacSub,'LineHandles');

if any(lhSag.Inport == -1)
    error("FOG v6 topology error: Sagnac input is disconnected.")
end

if any(lhSag.Outport == -1)
    error("FOG v6 topology error: Sagnac output is disconnected.")
end

disp("Sagnac polarization topology check: OK")

%% ============================================================
% PARAMETRY MODELU - RAPORT
%% ============================================================

fprintf("\nPOLARYZACJA v6 - PARAMETRY MODELU\n")
fprintf("---------------------------------\n")
fprintf("fiber               = standard SMF, %.0f m\n",L)
fprintf("polarizer ER        = %.1f dB\n",polarizer_ER_dB)
fprintf("V calibration       = %.6f\n",V_cal)
fprintf("depol residual      = %.3f\n",depol_residual)
fprintf("theta0              = %.2f deg\n",pol_theta0_rad*180/pi)
fprintf("theta amplitude     = %.2f deg\n",pol_theta_amp_rad*180/pi)
fprintf("delta0              = %.3f rad\n",pol_delta0_rad)
fprintf("delta amplitude     = %.3f rad\n",pol_delta_amp_rad)
fprintf("NR phase scale      = %.3e\n",pol_nr_scale)
fprintf("ADC                 = %d bit @ %.1f MS/s\n",adc_bits,fs_adc/1e6)
fprintf("AAF                 = %.0f kHz\n",f_aa_Hz/1e3)

%% ============================================================
% v6A - IDEALNA POLARYZACJA / TEST REGRESJI
%% ============================================================

disp("")
disp("==============================================")
disp(" v6A - IDEAL POLARIZATION REGRESSION")
disp("==============================================")

pol_enable = 0;
noise_enable = 0;
Omega_deg_s = 1;

Ts_solver = 0.05e-6;
updateNoiseSampling();

Tstop = 0.050;
Tmean_start = 0.040;

set_param( ...
    mdl, ...
    'SolverType','Fixed-step', ...
    'Solver','ode4', ...
    'FixedStep',sprintf('%.17g',Ts_solver), ...
    'StopTime',sprintf('%.17g',Tstop), ...
    'ReturnWorkspaceOutputs','on');

out = sim(mdl);

omega_ts = out.get('omega_est_ts');
vpol_ts = out.get('vpol_ts');
phipol_ts = out.get('phipol_ts');

idx = omega_ts.Time >= Tmean_start;

Omega_ideal = mean(omega_ts.Data(idx));
Omega_ideal_std = std(omega_ts.Data(idx));

idxV = vpol_ts.Time >= Tmean_start;
idxP = phipol_ts.Time >= Tmean_start;

V_ideal_mean = mean(vpol_ts.Data(idxV));
phi_ideal_max = max(abs(phipol_ts.Data(idxP)));

fprintf("Omega zadane         = %.9f deg/s\n",Omega_deg_s)
fprintf("Omega ideal          = %.9f deg/s\n",Omega_ideal)
fprintf("Blad                 = %+ .9e deg/s\n",Omega_ideal-Omega_deg_s)
fprintf("STD                  = %.9e deg/s\n",Omega_ideal_std)
fprintf("Vpol mean            = %.9f\n",V_ideal_mean)
fprintf("max |phi_pol|        = %.3e rad\n",phi_ideal_max)

baseline = table( ...
    Omega_deg_s, ...
    Omega_ideal, ...
    Omega_ideal-Omega_deg_s, ...
    Omega_ideal_std, ...
    V_cal, ...
    V_ideal_mean, ...
    phi_ideal_max, ...
    adc_bits, ...
    fs_adc/1e6, ...
    f_aa_Hz/1e3, ...
    'VariableNames', ...
    { ...
    'Omega_zadane_deg_s', ...
    'Omega_zmierzone_deg_s', ...
    'Blad_deg_s', ...
    'STD_deg_s', ...
    'V_cal', ...
    'Vpol_mean', ...
    'Max_abs_phi_pol_rad', ...
    'ADC_bits', ...
    'fs_MSps', ...
    'AAF_kHz' ...
    });

writetable(baseline,'FOG_v6_baseline.csv');

%% ============================================================
% v6B - SWEEP SKUTECZNOSCI DEPOLARYZACJI
%% ============================================================

disp("")
disp("==============================================")
disp(" v6B - DEPOLARIZER SENSITIVITY SWEEP")
disp("==============================================")

pol_enable = 1;
noise_enable = 0;

% Przywracamy dynamiczne zaburzenia.
pol_theta0_rad = 15*pi/180;
pol_theta_amp_rad = 20*pi/180;

pol_delta0_rad = 0.20;
pol_delta_amp_rad = 0.30;

depolSweep = [1.0 0.5 0.2 0.1 0.05 0.0]';
Nd = numel(depolSweep);

Ts_solver = 0.10e-6;
updateNoiseSampling();

TstopSweep = 0.080;
TmeanSweep = 0.040;

set_param( ...
    mdl, ...
    'FixedStep',sprintf('%.17g',Ts_solver), ...
    'StopTime',sprintf('%.17g',TstopSweep));

Vmean = zeros(Nd,1);
Vmin = zeros(Nd,1);
Vstd = zeros(Nd,1);

phiMean = zeros(Nd,1);
phiStd = zeros(Nd,1);
phiMaxAbs = zeros(Nd,1);

zeroMean = zeros(Nd,1);
zeroStd = zeros(Nd,1);

oneMean = zeros(Nd,1);
oneScaleErrorPct = zeros(Nd,1);

for k = 1:Nd

    depol_residual = depolSweep(k);

    % ZERO RATE
    Omega_deg_s = 0;
    out = sim(mdl);

    omega_ts = out.get('omega_est_ts');
    vpol_ts = out.get('vpol_ts');
    phipol_ts = out.get('phipol_ts');

    idxO = omega_ts.Time >= TmeanSweep;
    idxV = vpol_ts.Time >= TmeanSweep;
    idxP = phipol_ts.Time >= TmeanSweep;

    zeroMean(k) = mean(omega_ts.Data(idxO));
    zeroStd(k) = std(omega_ts.Data(idxO));

    Vmean(k) = mean(vpol_ts.Data(idxV));
    Vmin(k) = min(vpol_ts.Data(idxV));
    Vstd(k) = std(vpol_ts.Data(idxV));

    phiMean(k) = mean(phipol_ts.Data(idxP));
    phiStd(k) = std(phipol_ts.Data(idxP));
    phiMaxAbs(k) = max(abs(phipol_ts.Data(idxP)));

    % 1 deg/s - scale error
    Omega_deg_s = 1;
    out = sim(mdl);

    omega_ts = out.get('omega_est_ts');
    idxO = omega_ts.Time >= TmeanSweep;

    oneMean(k) = mean(omega_ts.Data(idxO));
    oneScaleErrorPct(k) = ...
        100*(oneMean(k)-1);

    fprintf( ...
        "r=%.2f: Vmin=%.5f, maxPhi=%.3e rad, zero=%+.3e, scaleErr=%+.4f %%\n", ...
        depol_residual,Vmin(k),phiMaxAbs(k), ...
        zeroMean(k),oneScaleErrorPct(k))
end

depolResults = table( ...
    depolSweep, ...
    Vmean, ...
    Vmin, ...
    Vstd, ...
    phiMean, ...
    phiStd, ...
    phiMaxAbs, ...
    zeroMean, ...
    zeroStd, ...
    oneMean, ...
    oneScaleErrorPct, ...
    'VariableNames', ...
    { ...
    'Depol_residual', ...
    'Vpol_mean', ...
    'Vpol_min', ...
    'Vpol_STD', ...
    'Phi_pol_mean_rad', ...
    'Phi_pol_STD_rad', ...
    'Phi_pol_max_abs_rad', ...
    'Zero_rate_mean_deg_s', ...
    'Zero_rate_STD_deg_s', ...
    'Omega_mean_at_1deg_s', ...
    'Scale_error_percent' ...
    });

writetable( ...
    depolResults, ...
    'FOG_v6_depolarizer_sweep.csv');

%% ============================================================
% v6C - MONTE CARLO LOSOWYCH STANOW SMF
%% ============================================================

disp("")
disp("==============================================")
disp(" v6C - RANDOM SMF POLARIZATION MONTE CARLO")
disp("==============================================")

% W tym tescie zaburzenie jest statyczne w pojedynczej realizacji,
% ale losowe pomiedzy realizacjami.
pol_theta_amp_rad = 0;
pol_delta_amp_rad = 0;

pol_theta_freq_Hz = 0;
pol_delta_freq_Hz = 0;

noise_enable = 1;
Omega_deg_s = 0;

residualMC = [1.0 0.2 0.1 0.05]';
Nr = numel(residualMC);
Nmc = 20;

Ts_solver = 0.20e-6;
updateNoiseSampling();

TstopMC = 0.040;
TmeanMC = 0.030;

set_param( ...
    mdl, ...
    'FixedStep',sprintf('%.17g',Ts_solver), ...
    'StopTime',sprintf('%.17g',TstopMC));

mcMean = zeros(Nr,1);
mcStd = zeros(Nr,1);
mcRMS = zeros(Nr,1);
mcMedianAbs = zeros(Nr,1);
mcP95Abs = zeros(Nr,1);
mcMaxAbs = zeros(Nr,1);
mcMeanV = zeros(Nr,1);

rng(6601);

for kr = 1:Nr

    depol_residual = residualMC(kr);

    vals = zeros(Nmc,1);
    visVals = zeros(Nmc,1);

    fprintf("\nr=%.2f: ",depol_residual)

    for irun = 1:Nmc

        % Losowe, ale ograniczone wzgledne stany polaryzacji.
        pol_theta0_rad = ...
            (-30 + 60*rand())*pi/180;

        pol_delta0_rad = ...
            -0.5 + rand();

        setSeeds( ...
            1600000 + 10000*kr + 10*irun);

        out = sim(mdl);

        omega_ts = out.get('omega_est_ts');
        vpol_ts = out.get('vpol_ts');

        idxO = omega_ts.Time >= TmeanMC;
        idxV = vpol_ts.Time >= TmeanMC;

        vals(irun) = mean(omega_ts.Data(idxO));
        visVals(irun) = mean(vpol_ts.Data(idxV));

        fprintf(".")
    end

    fprintf(" done")

    mcMean(kr) = mean(vals);
    mcStd(kr) = std(vals);
    mcRMS(kr) = sqrt(mean(vals.^2));

    absVals = abs(vals);
    mcMedianAbs(kr) = empiricalPercentile(absVals,50);
    mcP95Abs(kr) = empiricalPercentile(absVals,95);
    mcMaxAbs(kr) = max(absVals);

    mcMeanV(kr) = mean(visVals);
end

mcResults = table( ...
    residualMC, ...
    mcMean, ...
    mcStd, ...
    mcStd*3600, ...
    mcRMS, ...
    mcMedianAbs, ...
    mcP95Abs, ...
    mcMaxAbs, ...
    mcMeanV, ...
    'VariableNames', ...
    { ...
    'Depol_residual', ...
    'Zero_mean_deg_s', ...
    'Zero_STD_deg_s', ...
    'Zero_STD_deg_h', ...
    'Zero_RMS_deg_s', ...
    'Median_abs_Omega_deg_s', ...
    'P95_abs_Omega_deg_s', ...
    'Max_abs_Omega_deg_s', ...
    'Mean_visibility' ...
    });

disp("")
disp(mcResults)

writetable( ...
    mcResults, ...
    'FOG_v6_smf_monte_carlo.csv');

%% ============================================================
% v6D - DETEKCJA 0.0001 deg/s DLA NOMINALNEGO DEPOLARYZATORA
%% ============================================================

disp("")
disp("==============================================")
disp(" v6D - DETECTION WITH RANDOM SMF")
disp("==============================================")

depol_residual = 0.10;
Ndetect = 30;
OmegaSignal = 1e-4;

zeroVals = zeros(Ndetect,1);
signalVals = zeros(Ndetect,1);

rng(6610);

for irun = 1:Ndetect

    % Ta sama rodzina rozkladu stanow SMF, inne stany w kazdej klasie.
    pol_theta0_rad = ...
        (-30 + 60*rand())*pi/180;

    pol_delta0_rad = ...
        -0.5 + rand();

    Omega_deg_s = 0;

    setSeeds( ...
        1700000 + 10*irun);

    out = sim(mdl);
    omega_ts = out.get('omega_est_ts');

    idxO = omega_ts.Time >= TmeanMC;
    zeroVals(irun) = mean(omega_ts.Data(idxO));

    pol_theta0_rad = ...
        (-30 + 60*rand())*pi/180;

    pol_delta0_rad = ...
        -0.5 + rand();

    Omega_deg_s = OmegaSignal;

    setSeeds( ...
        1800000 + 10*irun);

    out = sim(mdl);
    omega_ts = out.get('omega_est_ts');

    idxO = omega_ts.Time >= TmeanMC;
    signalVals(irun) = mean(omega_ts.Data(idxO));

    if mod(irun,10) == 0 || irun == 1
        fprintf("run %2d/%2d\n",irun,Ndetect)
    end
end

zeroDetMean = mean(zeroVals);
zeroDetStd = std(zeroVals);

signalDetMean = mean(signalVals);
signalDetStd = std(signalVals);

signalDetBias = ...
    signalDetMean-OmegaSignal;

pooledSigma = ...
    sqrt((zeroDetStd^2+signalDetStd^2)/2);

classSeparation = ...
    abs(signalDetMean-zeroDetMean)/pooledSigma;

detectionResults = table( ...
    depol_residual, ...
    Ndetect, ...
    OmegaSignal, ...
    zeroDetMean, ...
    zeroDetStd, ...
    zeroDetStd*3600, ...
    3*zeroDetStd*3600, ...
    signalDetMean, ...
    signalDetStd, ...
    signalDetBias, ...
    classSeparation, ...
    'VariableNames', ...
    { ...
    'Depol_residual', ...
    'N_per_class', ...
    'Omega_signal_deg_s', ...
    'Zero_mean_deg_s', ...
    'Zero_STD_deg_s', ...
    'Zero_STD_deg_h', ...
    'Zero_3sigma_deg_h', ...
    'Signal_mean_deg_s', ...
    'Signal_STD_deg_s', ...
    'Signal_bias_deg_s', ...
    'Zero_signal_separation_sigma' ...
    });

disp(detectionResults)

writetable( ...
    detectionResults, ...
    'FOG_v6_detection_random_smf.csv');

%% ============================================================
% PARAMETRY MODELU DO CSV
%% ============================================================

parameter = [ ...
    "fiber_length_m"; ...
    "fiber_type"; ...
    "polarizer_ER_dB"; ...
    "V_cal"; ...
    "depol_nominal_residual"; ...
    "pol_nr_scale"; ...
    "theta_dynamic_amp_deg"; ...
    "delta_dynamic_amp_rad"; ...
    "ADC_bits"; ...
    "ADC_fs_MSps"; ...
    "AAF_kHz"; ...
    "f_mod_kHz" ...
    ];

value = [ ...
    string(L); ...
    "standard SMF"; ...
    string(polarizer_ER_dB); ...
    string(V_cal); ...
    "0.10"; ...
    string(pol_nr_scale); ...
    "20"; ...
    "0.30"; ...
    string(adc_bits); ...
    string(fs_adc/1e6); ...
    string(f_aa_Hz/1e3); ...
    string(f_mod/1e3) ...
    ];

note = [ ...
    "model"; ...
    "non-PM coil"; ...
    "assumption, not BOM"; ...
    "DSP calibration visibility"; ...
    "phenomenological, not catalog DOP"; ...
    "phenomenological, requires calibration"; ...
    "accelerated sensitivity test"; ...
    "accelerated sensitivity test"; ...
    "v5.1 preferred"; ...
    "v5.1 nominal"; ...
    "v5.1 working candidate"; ...
    "baseline modulation" ...
    ];

parameterTable = table(parameter,value,note);
writetable(parameterTable,'FOG_v6_model_parameters.csv');

%% ============================================================
% WYKRESY
%% ============================================================

figure('Name','FOG v6 - depolarizer visibility')

plot( ...
    depolSweep, ...
    Vmin, ...
    'o-', ...
    'LineWidth',1.5)

grid on
xlabel('Residual polarization sensitivity')
ylabel('Minimum visibility')
title('FOG v6 - visibility vs depolarizer residual')

figure('Name','FOG v6 - depolarizer zero bias')

semilogy( ...
    depolSweep, ...
    max(abs(zeroMean),eps), ...
    'o-', ...
    'LineWidth',1.5)

grid on
xlabel('Residual polarization sensitivity')
ylabel('|zero-rate mean| [deg/s]')
title('FOG v6 - polarization-induced zero bias')

figure('Name','FOG v6 - SMF Monte Carlo')

semilogy( ...
    residualMC, ...
    max(mcP95Abs,eps), ...
    'o-', ...
    'LineWidth',1.5)

grid on
xlabel('Residual polarization sensitivity')
ylabel('95 percentile |Omega| [deg/s]')
title('FOG v6 - random SMF polarization sensitivity')

%% ============================================================
% STAN KONCOWY MODELU = NOMINALNY v6
%% ============================================================

pol_enable = 1;
depol_residual = 0.10;

pol_theta0_rad = 15*pi/180;
pol_theta_amp_rad = 20*pi/180;

pol_delta0_rad = 0.20;
pol_delta_amp_rad = 0.30;

pol_theta_freq_Hz = 17;
pol_delta_freq_Hz = 23;

noise_enable = 1;
Omega_deg_s = 0;

Ts_solver = 0.05e-6;
updateNoiseSampling();

set_param( ...
    mdl, ...
    'FixedStep',sprintf('%.17g',Ts_solver), ...
    'StopTime','0.05');

save_system(mdl)
open_system(mdl)

disp("")
disp("==============================================")
disp(" FOG v6 - SYMULACJA ZAKONCZONA")
disp("==============================================")
disp("")
disp("Utworzono:")
disp("  FOG_v6.slx")
disp("  FOG_v6_baseline.csv")
disp("  FOG_v6_depolarizer_sweep.csv")
disp("  FOG_v6_smf_monte_carlo.csv")
disp("  FOG_v6_detection_random_smf.csv")
disp("  FOG_v6_model_parameters.csv")
disp("")
disp("WAZNE:")
disp("  v6 jest modelem wrazliwosciowym polaryzacji.")
disp("  depol_residual i pol_nr_scale trzeba pozniej")
disp("  skalibrowac eksperymentalnie dla realnego SMF/depolaryzatora.")
disp("")

%% ============================================================
% FUNKCJE
%% ============================================================

function buildSagnacV6(sub)

    Simulink.SubSystem.deleteContents(sub);

    add_block( ...
        'simulink/Ports & Subsystems/In1', ...
        [sub '/P_in'], ...
        'Port','1', ...
        'Position',[25 75 55 95]);

    add_block( ...
        'simulink/Ports & Subsystems/In1', ...
        [sub '/Omega_deg_s'], ...
        'Port','2', ...
        'Position',[25 285 55 305]);

    add_block( ...
        'simulink/Ports & Subsystems/Out1', ...
        [sub '/P_return'], ...
        'Port','1', ...
        'Position',[1040 80 1070 100]);

    add_block( ...
        'simulink/Ports & Subsystems/Out1', ...
        [sub '/Reference'], ...
        'Port','2', ...
        'Position',[1040 330 1070 350]);

    add_block( ...
        'simulink/Ports & Subsystems/Out1', ...
        [sub '/V_pol'], ...
        'Port','3', ...
        'Position',[1040 420 1070 440]);

    add_block( ...
        'simulink/Ports & Subsystems/Out1', ...
        [sub '/Phi_pol'], ...
        'Port','4', ...
        'Position',[1040 500 1070 520]);

    add_block( ...
        'simulink/Math Operations/Gain', ...
        [sub '/K2 + Loop Loss'], ...
        'Gain','K_sagnac_power', ...
        'Position',[100 55 220 105]);

    add_block( ...
        'simulink/Math Operations/Gain', ...
        [sub '/deg_to_rad'], ...
        'Gain','pi/180', ...
        'Position',[100 270 180 320]);

    add_block( ...
        'simulink/Math Operations/Gain', ...
        [sub '/Sagnac Phase'], ...
        'Gain','K_sag', ...
        'Position',[220 270 310 320]);

    add_block( ...
        'simulink/Sources/Sine Wave', ...
        [sub '/PZT phi_m'], ...
        'Amplitude','phi0', ...
        'Frequency','2*pi*f_mod', ...
        'Bias','0', ...
        'Phase','0', ...
        'SampleTime','0', ...
        'Position',[100 390 200 430]);

    add_block( ...
        'simulink/Continuous/Transport Delay', ...
        [sub '/CW-CCW Delay'], ...
        'DelayTime','tau', ...
        'Position',[270 410 380 450]);

    add_block( ...
        'simulink/Math Operations/Sum', ...
        [sub '/Delta phi mod'], ...
        'Inputs','+-', ...
        'Position',[440 365 475 445]);

    add_block( ...
        'simulink/Math Operations/Gain', ...
        [sub '/Reference Normalize'], ...
        'Gain','K_ref', ...
        'Position',[550 405 660 455]);

    % Polarization submodel.
    add_block( ...
        'simulink/Ports & Subsystems/Subsystem', ...
        [sub '/SMF Polarization'], ...
        'Position',[340 500 560 610]);

    buildPolarizationModel([sub '/SMF Polarization']);

    add_block( ...
        'simulink/Math Operations/Sum', ...
        [sub '/Total Phase'], ...
        'Inputs','+++', ...
        'Position',[610 245 650 335]);

    add_block( ...
        'simulink/Math Operations/Trigonometric Function', ...
        [sub '/Interference cos'], ...
        'Operator','cos', ...
        'Position',[700 260 790 310]);

    add_block( ...
        'simulink/Math Operations/Product', ...
        [sub '/Polarization Visibility'], ...
        'Position',[820 250 870 320]);

    add_block( ...
        'simulink/Math Operations/Bias', ...
        [sub '/Fringe +1'], ...
        'Bias','1', ...
        'Position',[900 260 970 310]);

    add_block( ...
        'simulink/Math Operations/Product', ...
        [sub '/Optical Interference'], ...
        'Position',[980 70 1030 130]);

    add_line(sub,'P_in/1','K2 + Loop Loss/1','autorouting','on');
    add_line(sub,'K2 + Loop Loss/1','Optical Interference/1','autorouting','on');

    add_line(sub,'Omega_deg_s/1','deg_to_rad/1','autorouting','on');
    add_line(sub,'deg_to_rad/1','Sagnac Phase/1','autorouting','on');
    add_line(sub,'Sagnac Phase/1','Total Phase/1','autorouting','on');

    add_line(sub,'PZT phi_m/1','Delta phi mod/1','autorouting','on');
    add_line(sub,'PZT phi_m/1','CW-CCW Delay/1','autorouting','on');
    add_line(sub,'CW-CCW Delay/1','Delta phi mod/2','autorouting','on');

    add_line(sub,'Delta phi mod/1','Total Phase/2','autorouting','on');
    add_line(sub,'Delta phi mod/1','Reference Normalize/1','autorouting','on');

    add_line(sub,'SMF Polarization/2','Total Phase/3','autorouting','on');

    add_line(sub,'Total Phase/1','Interference cos/1','autorouting','on');
    add_line(sub,'Interference cos/1','Polarization Visibility/1','autorouting','on');
    add_line(sub,'SMF Polarization/1','Polarization Visibility/2','autorouting','on');
    add_line(sub,'Polarization Visibility/1','Fringe +1/1','autorouting','on');
    add_line(sub,'Fringe +1/1','Optical Interference/2','autorouting','on');

    add_line(sub,'Optical Interference/1','P_return/1','autorouting','on');
    add_line(sub,'Reference Normalize/1','Reference/1','autorouting','on');

    add_line(sub,'SMF Polarization/1','V_pol/1','autorouting','on');
    add_line(sub,'SMF Polarization/2','Phi_pol/1','autorouting','on');
end

function buildPolarizationModel(sub)

    Simulink.SubSystem.deleteContents(sub);

    % theta(t)
    add_block( ...
        'simulink/Sources/Sine Wave', ...
        [sub '/SMF Axis Coupling theta'], ...
        'Amplitude','pol_theta_amp_rad', ...
        'Frequency','2*pi*pol_theta_freq_Hz', ...
        'Bias','pol_theta0_rad', ...
        'Phase','0', ...
        'SampleTime','0', ...
        'Position',[40 55 160 95]);

    % delta(t)
    add_block( ...
        'simulink/Sources/Sine Wave', ...
        [sub '/SMF Birefringence delta'], ...
        'Amplitude','pol_delta_amp_rad', ...
        'Frequency','2*pi*pol_delta_freq_Hz', ...
        'Bias','pol_delta0_rad', ...
        'Phase','pol_delta_phase_rad', ...
        'SampleTime','0', ...
        'Position',[40 220 160 260]);

    add_block( ...
        'simulink/Math Operations/Trigonometric Function', ...
        [sub '/cos theta'], ...
        'Operator','cos', ...
        'Position',[220 25 290 65]);

    add_block( ...
        'simulink/Math Operations/Trigonometric Function', ...
        [sub '/sin theta'], ...
        'Operator','sin', ...
        'Position',[220 95 290 135]);

    add_block( ...
        'simulink/Math Operations/Product', ...
        [sub '/cos2 theta'], ...
        'Position',[340 25 390 75]);

    add_block( ...
        'simulink/Math Operations/Product', ...
        [sub '/sin2 theta'], ...
        'Position',[340 95 390 145]);

    add_block( ...
        'simulink/Math Operations/Gain', ...
        [sub '/2 delta'], ...
        'Gain','2', ...
        'Position',[220 215 290 265]);

    add_block( ...
        'simulink/Math Operations/Trigonometric Function', ...
        [sub '/cos 2delta'], ...
        'Operator','cos', ...
        'Position',[340 195 420 235]);

    add_block( ...
        'simulink/Math Operations/Trigonometric Function', ...
        [sub '/sin 2delta'], ...
        'Operator','sin', ...
        'Position',[340 255 420 295]);

    add_block( ...
        'simulink/Math Operations/Product', ...
        [sub '/s2 cos2d'], ...
        'Position',[480 155 530 205]);

    add_block( ...
        'simulink/Math Operations/Sum', ...
        [sub '/Gamma real'], ...
        'Inputs','++', ...
        'Position',[590 80 630 155]);

    add_block( ...
        'simulink/Math Operations/Product', ...
        [sub '/Gamma imag'], ...
        'Position',[480 245 530 295]);

    add_block( ...
        'simulink/Math Operations/Product', ...
        [sub '/real squared'], ...
        'Position',[680 60 730 110]);

    add_block( ...
        'simulink/Math Operations/Product', ...
        [sub '/imag squared'], ...
        'Position',[680 145 730 195]);

    add_block( ...
        'simulink/Math Operations/Sum', ...
        [sub '/Gamma abs squared'], ...
        'Inputs','++', ...
        'Position',[775 85 815 165]);

    add_block( ...
        'simulink/Math Operations/Math Function', ...
        [sub '/Gamma magnitude'], ...
        'Operator','sqrt', ...
        'Position',[860 100 950 150]);

    % phi_raw = atan(imag/real)
    add_block( ...
        'simulink/Math Operations/Product', ...
        [sub '/imag over real'], ...
        'Inputs','*/', ...
        'Position',[680 245 730 295]);

    add_block( ...
        'simulink/Math Operations/Trigonometric Function', ...
        [sub '/Gamma phase'], ...
        'Operator','atan', ...
        'Position',[780 250 850 290]);

    % Vpol = V_cal * [1 - pol_enable*depol_residual*(1-|Gamma|)]
    add_block( ...
        'simulink/Sources/Constant', ...
        [sub '/One V'], ...
        'Value','1', ...
        'Position',[1000 20 1040 50]);

    add_block( ...
        'simulink/Math Operations/Sum', ...
        [sub '/1 minus Gamma magnitude'], ...
        'Inputs','+-', ...
        'Position',[1010 85 1050 145]);

    add_block( ...
        'simulink/Math Operations/Gain', ...
        [sub '/Residual Visibility'], ...
        'Gain','pol_enable*depol_residual', ...
        'Position',[1100 90 1210 140]);

    add_block( ...
        'simulink/Math Operations/Sum', ...
        [sub '/Visibility suppression'], ...
        'Inputs','+-', ...
        'Position',[1260 55 1300 125]);

    add_block( ...
        'simulink/Math Operations/Gain', ...
        [sub '/Polarizer calibration visibility'], ...
        'Gain','V_cal', ...
        'Position',[1350 65 1480 115]);

    % phi_pol = residual * calibrated small nonreciprocal fraction
    add_block( ...
        'simulink/Math Operations/Gain', ...
        [sub '/Polarization NR Scale'], ...
        'Gain','pol_enable*depol_residual*pol_nr_scale', ...
        'Position',[940 245 1110 295]);

    add_block( ...
        'simulink/Ports & Subsystems/Out1', ...
        [sub '/V_pol'], ...
        'Port','1', ...
        'Position',[1550 78 1580 102]);

    add_block( ...
        'simulink/Ports & Subsystems/Out1', ...
        [sub '/Phi_pol'], ...
        'Port','2', ...
        'Position',[1180 258 1210 282]);

    % theta
    add_line(sub,'SMF Axis Coupling theta/1','cos theta/1','autorouting','on');
    add_line(sub,'SMF Axis Coupling theta/1','sin theta/1','autorouting','on');

    add_line(sub,'cos theta/1','cos2 theta/1','autorouting','on');
    add_line(sub,'cos theta/1','cos2 theta/2','autorouting','on');

    add_line(sub,'sin theta/1','sin2 theta/1','autorouting','on');
    add_line(sub,'sin theta/1','sin2 theta/2','autorouting','on');

    % delta
    add_line(sub,'SMF Birefringence delta/1','2 delta/1','autorouting','on');
    add_line(sub,'2 delta/1','cos 2delta/1','autorouting','on');
    add_line(sub,'2 delta/1','sin 2delta/1','autorouting','on');

    % real Gamma
    add_line(sub,'sin2 theta/1','s2 cos2d/1','autorouting','on');
    add_line(sub,'cos 2delta/1','s2 cos2d/2','autorouting','on');

    add_line(sub,'cos2 theta/1','Gamma real/1','autorouting','on');
    add_line(sub,'s2 cos2d/1','Gamma real/2','autorouting','on');

    % imag Gamma
    add_line(sub,'sin2 theta/1','Gamma imag/1','autorouting','on');
    add_line(sub,'sin 2delta/1','Gamma imag/2','autorouting','on');

    % magnitude
    add_line(sub,'Gamma real/1','real squared/1','autorouting','on');
    add_line(sub,'Gamma real/1','real squared/2','autorouting','on');

    add_line(sub,'Gamma imag/1','imag squared/1','autorouting','on');
    add_line(sub,'Gamma imag/1','imag squared/2','autorouting','on');

    add_line(sub,'real squared/1','Gamma abs squared/1','autorouting','on');
    add_line(sub,'imag squared/1','Gamma abs squared/2','autorouting','on');

    add_line(sub,'Gamma abs squared/1','Gamma magnitude/1','autorouting','on');

    % phase
    add_line(sub,'Gamma imag/1','imag over real/1','autorouting','on');
    add_line(sub,'Gamma real/1','imag over real/2','autorouting','on');
    add_line(sub,'imag over real/1','Gamma phase/1','autorouting','on');
    add_line(sub,'Gamma phase/1','Polarization NR Scale/1','autorouting','on');

    % visibility
    add_line(sub,'One V/1','1 minus Gamma magnitude/1','autorouting','on');
    add_line(sub,'Gamma magnitude/1','1 minus Gamma magnitude/2','autorouting','on');

    add_line(sub,'1 minus Gamma magnitude/1','Residual Visibility/1','autorouting','on');

    add_line(sub,'One V/1','Visibility suppression/1','autorouting','on');
    add_line(sub,'Residual Visibility/1','Visibility suppression/2','autorouting','on');

    add_line(sub,'Visibility suppression/1','Polarizer calibration visibility/1','autorouting','on');
    add_line(sub,'Polarizer calibration visibility/1','V_pol/1','autorouting','on');

    add_line(sub,'Polarization NR Scale/1','Phi_pol/1','autorouting','on');
end

function updateNoiseSampling()

    Ts_l = evalin('caller','Ts_solver');

    i_dark_l = evalin('caller','i_dark_shot_ASD');
    i_johnson_l = evalin('caller','i_johnson_ASD');
    i_opampi_l = evalin('caller','i_opamp_current_ASD');
    i_opampe_l = evalin('caller','i_opamp_voltage_eq_ASD');

    scale_l = 1/sqrt(2*Ts_l);

    assignin('caller','Ts_noise',Ts_l);
    assignin('caller','noise_sample_scale',scale_l);

    assignin( ...
        'caller','sigma_dark_sample_A', ...
        i_dark_l*scale_l);

    assignin( ...
        'caller','sigma_johnson_sample_A', ...
        i_johnson_l*scale_l);

    assignin( ...
        'caller','sigma_opamp_current_sample_A', ...
        i_opampi_l*scale_l);

    assignin( ...
        'caller','sigma_opamp_voltage_sample_A', ...
        i_opampe_l*scale_l);
end

function setSeeds(baseSeed)

    assignin('caller','seed_photo',baseSeed+1);
    assignin('caller','seed_dark',baseSeed+2);
    assignin('caller','seed_johnson',baseSeed+3);
    assignin('caller','seed_opamp_i',baseSeed+4);
    assignin('caller','seed_opamp_en',baseSeed+5);
end

function q = empiricalPercentile(x,p)

    x = sort(x(:));
    n = numel(x);

    if n == 0
        q = NaN;
        return
    end

    if n == 1
        q = x(1);
        return
    end

    pos = 1 + (n-1)*(p/100);
    i0 = floor(pos);
    i1 = ceil(pos);

    if i0 == i1
        q = x(i0);
    else
        w = pos-i0;
        q = (1-w)*x(i0) + w*x(i1);
    end
end
